### ISSUE TITLE
Dapr GRPC proxy connection leak

### ISSUE THREAD

**Issue by jsheetzmt** [dapr/dapr#6734] opened 2023-07-27 15:40 UTC
## In what area(s)?

> /area runtime 
## What version of Dapr?

> 1.1.x

## Expected Behavior

Proxying GRPC calls through dapr sidecar doesn't open many connections to destination app during load

## Actual Behavior

During load, dapr sidecar is opening many connections to the destination app causing high TCP usage and memory leak in our .NET Core application. When I remove the dapr sidecar and make a direct connection between the server and client, I only have a single connection open on port 8081 (HTTP2 traffic).

**dotnet-monitor**
![image](https://github.com/dapr/dapr/assets/103272899/85125f6e-f3ba-410a-bb29-dd7216e363b5)

**ss**
![image](https://github.com/dapr/dapr/assets/103272899/744477ea-8781-41a4-bf81-b40c27022d5b)

## Steps to Reproduce the Problem

Proxy GRPC calls through dapr sidecar with high load

## Possible related issue
https://github.com/dapr/dapr/issues/4937

**Comment by yaron2** [comment] 2023-07-27 16:29
So to be clear, in the following call chain: App 1 --> Dapr 1 -------> Dapr 2 --> App 2

You see connections being opened and not re-used in the path of Dapr 2 --> App 2?

**Comment by jsheetzmt** [comment] 2023-07-27 16:43
Yep, that is exactly right @yaron2 but there is some connection reuse between Dapr 2 --> App 2. If I am doing a single request at a time in something like Postman, connection count stays at 1. As soon as I throw JMeter with 10 threads at it, connection count grows steadily, but it doesn't increase by 1 for every request.

**Comment by yaron2** [comment] 2023-07-27 16:49
Does the connection count continue growing after you've finished opening the 10 threads with JMeter?

**Comment by jsheetzmt** [comment] 2023-07-27 16:54
It stops growing but the connections remain open.

![image](https://github.com/dapr/dapr/assets/103272899/5384f918-2a8b-4577-a974-d18c44be5aca)

**Comment by yaron2** [comment] 2023-07-27 16:57
Ok thanks a lot of the info, will check this out. Do you have any special connection max age/timeout settings on App 2's server?

**Comment by jsheetzmt** [comment] 2023-07-27 16:59
I have this configured to keep alive the HTTP2 connection so it doesn't die while idle. I tried without this logic and still saw the same behavior with dapr sidecar --> App 2

```
private static readonly SocketsHttpHandler _handler = new SocketsHttpHandler
{
    PooledConnectionIdleTimeout = Timeout.InfiniteTimeSpan,
    KeepAlivePingDelay = TimeSpan.FromSeconds(60),
    KeepAlivePingTimeout = TimeSpan.FromSeconds(30),
    EnableMultipleHttp2Connections = true
};
```

**Comment by yaron2** [comment] 2023-08-01 23:27
I believe i'm able to reproduce this locally.. tracking this for 1.12 @jsheetzmt.

**Comment by jsheetzmt** [comment] 2023-08-02 14:47
Awesome, thanks for the update @yaron2!

**Comment by yaron2** [comment] 2023-08-02 17:59
@jsheetzmt I've made some progress and am able to correlate new connection creation to the number of parallel requests coming in to the app. Can you provide more details on the concurrency parameters for your JMeter test?

**Comment by jsheetzmt** [comment] 2023-08-02 18:38
With the 10 threads, I was just letting it run indefinitely and would see a new connection every 100 requests or so. Each thread sends one request to the app, gets the response and then repeats the test.

**Comment by yaron2** [comment] 2023-08-02 18:39
And how long would it take to for 100 requests to come back?

**Comment by yaron2** [comment] 2023-08-02 19:08
@jsheetzmt it looks like you're seeing a new connection opening up due to this setting: https://github.com/dapr/dapr/blob/e3032618c6c350d9ee56bbf98dc17625b329ef3b/pkg/grpc/pool.go#L32.

Essentially Dapr would open a new connection if the current one holds 100 streams in a Dapr to App connection.

**Comment by jsheetzmt** [comment] 2023-08-02 19:10
Interesting. Do you know why the sidecar is opening a new stream and not reusing an existing one?

**Comment by jsheetzmt** [comment] 2023-08-02 19:15
When I change App 1's URL to go to App 2 directly (not dapr sidecar), there's only a single connection open on App 2.

**Comment by yaron2** [comment] 2023-08-02 19:27
It looks like we're treating every request as a stream when incrementing the counter. cc @ItalyPaleAle to chime in on that.

**Comment by jsheetzmt** [comment] 2023-08-02 19:30
@yaron2 Would you expect connections to close after a certain period of a time? Right now, it seems like connections ramp up and never ramp down. Would always like a min connection of 1 to keep the connection warm

**Comment by yaron2** [comment] 2023-08-02 19:31
> @yaron2 Would you expect connections to close after a certain period of a time? Right now, it seems like connections ramp up and never ramp down. Would always like a min connection of 1 to keep the connection warm

We have a max connection age of 3 minutes. If there's keep alive enabled on your app server, it *might* mess with that.

**Comment by jsheetzmt** [comment] 2023-08-02 19:40
Okay, I might have to play around with that some more. We have keep alive on our clients but not the server. Even when I disable the client's keep alive, I am not seeing total connections drop back down.

**Comment by ItalyPaleAle** [comment] 2023-08-02 19:47
> It looks like we're treating every request as a stream when incrementing the counter. cc @ItalyPaleAle to chime in on that.

In the context of `grpcMaxConcurrentStreams`, "stream" refers to HTTP/2 streams, not to gRPC streaming RPC. Each gRPC RPC uses a HTTP/2 stream underlying (even unary RPCs use a stream in HTTP/2)

**Comment by yaron2** [comment] 2023-08-02 20:40
So the next question is why does Dapr dial a new connection to talk to the app every for 100 RPCs per connection? When a Dapr SDK talks to Dapr via gRPC, or when users open native gRPC clients, or even when users use gRPC without Dapr, this logic isn't present.

**Comment by ItalyPaleAle** [comment] 2023-08-02 21:05
@yaron2 

It's been a while so I don't recall 100% of details but from memory, and from some refreshing Google searches, it was probably related to:

**First.** The need to ensure better load balancing across multiple apps. Before we were closing connections right after they were used, so each RPC was creating a new connection so it was connecting to (possibly) a different sidecar. If we keep connections open, the worry was that it may not load balance. However, in hindsight I wonder if this was some sort of premature optimization and maybe the gRPC SDK does that already?

**Second.** From the [gRPC docs](https://grpc.io/docs/guides/performance/)

![image](https://github.com/dapr/dapr/assets/43508/82acc857-62b2-49a3-9ec4-ccb863154128)

**Comment by yaron2** [comment] 2023-08-02 21:15
> However, in hindsight I wonder if this was some sort of premature optimization and maybe the gRPC SDK does that already?

This should be done by gRPC based on our `dns://` schema in combination with the max connection age, that should most probably be reduced from 3m to a much lower value.

The 2nd point of the gRPC docs is relevant, however I can confirm (and also @jsheetzmt) that if you open a client/server dial, you do not see additional TCP connection beyond 100.

My conclusion is this: if load balancing isn't affected, we should default to remove this logic by default and make it configurable to allow users to handle special cases that may suffer due to queuing.

**Comment by ItalyPaleAle** [comment] 2023-08-02 21:21
> This should be done by gRPC based on our dns:// schema in combination with the max connection age (which should most probably be reduced from 3m to a much lower value).

Yes, using `dns://` causes gRPC to round-robin when establishing a connection. I am just not sure what happens if the connection is not closed every time (like it used to in the past): will it still send each request to a different app?

Some testing may help figuring out if the additional pooling we're doing is needed or not.

**Comment by yaron2** [comment] 2023-08-02 21:24
> Some testing may help figuring out if the additional pooling we're doing is needed or not.

Indeed, but for Dapr to app channel where there's expected to be a single endpoint for the app (most of the time, anyway), this should likely skip this logic by default and be made configurable. Testing is definitely needed to see if this is also the case for Dapr to Dapr communication.

**Comment by jsheetzmt** [comment] 2023-08-02 21:34
We are using Dapr in Azure Container Apps, and we will have scaling so that we spin up additional replicas during load and ideally that traffic is load balanced across the replicas.

**Comment by ItalyPaleAle** [comment] 2023-08-02 21:36
> Indeed, but for Dapr to app channel where there's expected to be a single endpoint for the app (most of the time, anyway), this should likely skip this logic by default and be made configurable. 

Oh, yes. I was primarily fixated on sidecar-to-sidecar. sidecar-to-app can be different

**Comment by yaron2** [comment] 2023-08-02 21:56
> We are using Dapr in Azure Container Apps, and we will have scaling so that we spin up additional replicas during load and ideally that traffic is load balanced across the replicas. I would expect each replica to have a connection open to Dapr sidecar, and the side car is still doing round-robin

That is a valid expectation

**Closed** 2023-08-04 21:13 UTC
Labels: kind/bug, P1

**Comment by jsheetzmt** [comment] 2023-09-07 21:45
@yaron2 Pulled down the nightly and things are looking much, much better now. Thank you!
