### ISSUE TITLE
Service Invocation API repeats headers in response for certain response types

### ISSUE THREAD

**Issue by whytem** [dapr/dapr#7434] opened 2024-01-23 18:02 UTC
## In what area(s)?
/area runtime

## What version of Dapr?

1.12.4

## Expected Behavior

When making a request the service invocation API, the headers in the response should mirror the underlying the service and not be repeated. For example, the response to a direct request such as 

curl -v http://localhost:5000/download/missing_file.xls

should be largely the same as a request made through through the service invocation API

curl -v http://localhost:3500/v1.0/invoke/fileservice/method/download/missing_file.xls

## Actual Behavior

Instead certain headers are repeated in the responses with certain status code (i.e. 404 shown below). The repeated headers is causing proxy (YARP) to fail with the error 

**Direct Invocation**
```
# curl -v http://localhost:5000/download/missing_file.xls
*   Trying 127.0.0.1:5000...
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /download/missing_file.xls HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.88.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< date: Tue, 23 Jan 2024 17:45:29 GMT
< server: uvicorn
< content-length: 22
< content-type: application/json
< 
* Connection #0 to host localhost left intact
{"detail":"Not Found"}
```

**Service API Invocation**
```
# curl -v http://localhost:3500/v1.0/invoke/fileservice/method/download/missing_file.xlsnload/missing_file.xls
*   Trying 127.0.0.1:3500...
* Connected to localhost (127.0.0.1) port 3500 (#0)
> GET /v1.0/invoke/fileservice/method/download/missing_file.xls HTTP/1.1
> Host: localhost:3500
> User-Agent: curl/7.88.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Length: 22                                 NOTE: REPEATED HEADER
< Content-Length: 22
< Content-Type: application/json
< Date: Tue, 23 Jan 2024 17:45:59 GMT     NOTE: REPEATED HEADER
< Date: Tue, 23 Jan 2024 17:45:59 GMT
< Server: uvicorn                                        NOTE: REPEATED HEADER
< Server: uvicorn
< Traceparent: 00-00000000000000000000000000000000-0000000000000000-00
< Traceparent: 00-00000000000000000000000000000000-0000000000000000-00
< 
* Connection #0 to host localhost left intact
{"detail":"Not Found"}
```

_PROXY ERROR:_

warn: Yarp.ReverseProxy.Forwarder.HttpForwarder[48]
      ResponseHeaders: The destination returned a response that cannot be proxied back to the client.
      System.InvalidOperationException: Invalid Content-Length: "22,22". Value must be a positive integral number.

## Steps to Reproduce the Problem

Make a GET request to an endpoint which produces a 404 status code. The headers are not repeated in request with a successful status code (e.g. 200)

**Comment by yaron2** [comment] 2024-01-23 21:23
Duplicate of https://github.com/dapr/dapr/issues/7371.

This was fixed and will come out in Dapr 1.13.

**Closed by yaron2** 2024-01-23 21:23 UTC
Labels: kind/bug
