### ISSUE TITLE
[Workflow] Calls to GetWorkflowAsync or TerminateWorkflowAsync don't return

### ISSUE THREAD

**Issue by clintsinger** [dapr/dapr#6435] opened 2023-06-01 22:54 UTC
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

dapr runtime: 1.11.0-rc.7
dotnet SDK: 1.11.0-rc01

## Expected Behavior

When calling either the `GetWorkflowAsync` or the `TerminateWorkflowAsync ` it is expected that they execute and immediately return.

## Actual Behavior

I regularly get into a situation where calls to either of those methods enter but never return.   There doesn't appear to be any indication in the daprd logs stating what is happening, from what I can see.

## Release Note

RELEASE NOTE:
[dapr-workflow-dapr.txt](https://github.com/dapr/dapr/files/11636756/dapr-workflow-dapr.txt)
[dapr-workflow-dotnet.txt](https://github.com/dapr/dapr/files/11636757/dapr-workflow-dotnet.txt)

**Comment by yaron2** [comment] 2023-06-01 23:44
cc @cgillum

**Comment by cgillum** [comment] 2023-06-02 00:06
@clintsinger I haven't seen this before. Do you have a way to reliably reproduce it?

**Comment by clintsinger** [comment] 2023-06-02 15:33
I'm able to reproduce it every time in my own project.  I'll see if I can create a smaller repro. 

I have since updated the original issue with more details about the versions and attached the logs from my dotnet side and corresponding daprd side (filtering on the word "work)

**Comment by clintsinger** [comment] 2023-06-05 00:39
I have created a repro project at https://github.com/clintsinger/dapr-issue6435.  

I use Visual Studio and Container Tools and the project was built and tested using that setup.

When running the project you will notice that it will run for a short while and then at some point it will get stuck.   I have run it repeatedly and the results are always the same.

**Comment by cgillum** [comment] 2023-06-06 23:14
I was able to reproduce the problem locally using the docker-compose configuration for this project. I suspect that this could be an issue where the workflow actor is somehow getting locked indefinitely. I'll try to see if I can reproduce this with a debugger attached.

**Comment by cgillum** [comment] 2023-06-07 00:34
I reproduced the issue with a debugger attached, and the problem is that the workflow actor is in a locked state, preventing any other access to that actor (including GetWorkflow and TerminateWorkflow calls). I'm currently trying to figure out why the actor is in a locked state.

**Comment by cgillum** [comment] 2023-06-07 02:00
I've confirmed that this is a bug in the workflow engine. It's an actor reentrancy deadlock that can occur in certain conditions when an app quickly reuses workflow IDs, which is exactly what this repro app is doing. Calls to `GetWorkflowAsync` and `TerminateWorkflowAsync` will hang when a workflow actor gets into this deadlocked state.

I'll work on a fix for this ASAP.

FYI @yaron2 @artursouza

**Comment by clintsinger** [comment] 2023-06-07 14:02
I'm glad you were able to find the issue so quickly.  Yes, I'll be able to test a fix once it is ready.

**Comment by mukundansundar** [comment] 2023-06-27 16:05
closed by #6455

**Closed by mukundansundar** 2023-06-27 16:05 UTC
Labels: kind/bug
