### ISSUE TITLE
Operator unable to see secrets across namespaces when processing component updates - K8s

### ISSUE THREAD

**Issue by slacksach** [dapr/dapr#3949] opened 2021-11-25 12:45 UTC
It appears as though the Dapr Operator is looking for secrets in the wrong place when processing component updates for components in different namespaces.
`
{"instance":"dapr-operator-76db4d6d4f-8qsf8","level":"warning","msg":"error processing component {name}: Secret \"{secretname}\" not found","scope":"dapr.operator.api","time":"2021-11-25T10:04:03.97648577Z","type":"log","ver":"unknown"}
`

The secrets do exist and are in the relevant namespaces with the components.

## In what area(s)?
/area operator

## What version of Dapr?
1.5.x

## Expected Behavior
Operator should not fail when loading components

## Actual Behavior
Operator error when loading components, logged as missing secrets even when secrets exist

## Steps to Reproduce the Problem
Deploy dapr v1.5.x
Deploy a pod with a component which references a secret in a separate namespace
Trigger component update from operator

## Release Note
Fix Operator component update

**Comment by yaron2** [comment] 2021-11-25 17:48
@slacksach just to be clear, Dapr today does not in-place update components. Components can be added or removed to an existing sidecar without a restart to the `daprd` process/container, but updates will not get applied.

Regardless, this issue should be fixed. When you write `Trigger component update from operator`, do you mean change a field in the schema of the component?

**Comment by swoop-admin** [comment] 2021-11-25 21:56
Hi @yaron2, I think I may actually close this issue as it is potentially caused by our Secrets operator which automatically refreshes secrets and might be doing so when the operator is checking components causing the missing updates.

It might be worth a docs upgrade just to say that the dapr-secret-reader role only applies to the original namespace and as such for any subsequent namespaces containing Dapr annotations for injection will require this RBAC permission applied to the default service account.

In answer to the question, yes, in my testing any update to the object, labels, annotations etc triggered the behaviour.

**Comment by slacksach** [comment] 2021-11-25 21:58
Hi @yaron2, I think I may actually close this issue as it is potentially caused by our Secrets operator which automatically refreshes secrets and might be doing so when the operator is checking components causing the missing updates.

It might be worth a docs upgrade just to say that the dapr-secret-reader role only applies to the original namespace and as such for any subsequent namespaces containing Dapr annotations for injection will require this RBAC permission applied to the default service account.

In answer to the question, yes, in my testing any update to the object, labels, annotations etc triggered the behaviour.

**Comment by yaron2** [comment] 2021-11-25 23:44
> Hi @yaron2, I think I may actually close this issue as it is potentially caused by our Secrets operator which automatically refreshes secrets and might be doing so when the operator is checking components causing the missing secret messages.
> 
> On a secrets related note, It might be worth a small docs update just to say that the dapr-secret-reader role only applies to the original namespace and as such for any subsequent namespaces containing Dapr annotations for injection will require this RBAC permission applied to the default service account.
> 
> In answer to the question, yes, in my testing any update to the object, labels, annotations etc triggered the behaviour.

Ok. While submitting a [PR](https://github.com/dapr/dapr/pull/3952) for this I actually found a different issue and changed my PR to account for that. I'm closing this for now.

**Closed by yaron2** 2021-11-25 23:44 UTC
Labels: kind/bug
