### ISSUE TITLE
Improve Logging for Pub/Sub 

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/dapr#1340] opened 2020-03-30 14:01 UTC
## In what area(s)?

/area runtime
/area docs

## What version of Dapr?

Current master: v0.3.0-rc.0-193-g2b9ea797-dirty

## Expected Behavior

- Docs
  - it is documented which HTTP status codes are expected at [/dapr/subscribe](https://github.com/dapr/docs/blob/master/reference/api/pubsub_api.md#provide-a-route-for-dapr-to-discover-topic-subscriptions)
  - it is documented which HTTP status codes are expected at [/[topic_name]](https://github.com/dapr/docs/blob/master/reference/api/pubsub_api.md#provide-routes-for-dapr-to-deliver-topic-events)
- Runtime
  - the Dapr runtime - and the developer - can distinguish between:
    1. the app does not want to subscribe to topics
    2. there was an error generating the list of subscribed topics
  - the Dapr runtime - and the developer - can distinguish between:
    1. the app tried to process the pubsub message but was not able to do it and want Dapr to try it again (or maybe put it into a deadletter queue)
    2. the app was wrongly configured and did not received the pubsub message at all, e.g. wrong routing (404), enabled auth by mistake (401 at the topic route) or Dapr could not reach the app at all

## Actual Behavior

- HTTP status codes not documented / specified in the protocol (see above)
- any response other then 200 is ignored at ```/dapr/subscribe``` (https://github.com/dapr/dapr/blob/master/pkg/runtime/runtime.go#L754)
- any response other then 200 at ```/[topic_name]``` is only logged on level Debug and does not return any useful information (https://github.com/dapr/dapr/blob/master/pkg/runtime/runtime.go#L944)
  - ```res.status(500).send({ error: "hello world" })```
gives the following:
```== DAPR == time="2020-03-30T15:32:13.4326793+02:00" level=debug msg="error from app consumer: %!s(<nil>)" app_id=node-subscriber instance=XYZ scope=dapr.runtime type=log ver=edge```

## Steps to Reproduce the Problem

Use the [PubSub sample](https://github.com/dapr/samples/tree/master/4.pub-sub) and return some errors:
```js
app.get('/dapr/subscribe', (_req, res) => {
    res.json([
        'A',
        'B'
    ]);

    //res.sendStatus(404);
    //res.sendStatus(401);
    //res.sendStatus(500);
});

app.post('/A', (req, res) => {
    // console.log("A: ", req.body);
    // res.sendStatus(200);

    //res.sendStatus(401);
    //res.sendStatus(500);
    res.status(500).send({ error: "hello world" });
});
```

## Proposal: Logging

- Warning Log Level
  - requests to ```/dapr/subscribe``` not responding with 200 or 404 will be logged with status code
  - requests to ```/[topic name]``` not responding with 200 or 503 will be logged with status code and topic name
- Debug Log Level (in addition)
  - requests to ```/dapr/subscribe``` not responding with 200 will be logged with status code and content
  - requests to ```/[topic name]``` not responding with 200 will be logged with status code and content and topic name

**Breaking change?**
This will not be a breaking change, because the additional HTTP response codes only influence the logging.

#### Provide a route for Dapr to discover topic subscriptions

Dapr will invoke the following endpoint on user code to discover topic subscriptions:

##### HTTP Request

```http
GET http://localhost:<appPort>/dapr/subscribe
```

##### HTTP Response codes

Code | Description
---- | -----------
200  | Application subscribes to the responded topics
404  | Application does not subscribe to any topic

##### URL Parameters

Parameter | Description
--------- | -----------
appPort | the application port

##### HTTP Response body

A json encoded array of strings.

Example:

```json
"["TopicA","TopicB"]"
```

#### Provide route(s) for Dapr to deliver topic events

In order to deliver topic events, a `POST` call will be made to user code with the name of the topic as the URL path.

The following example illustrates this point, considering a subscription for topic `TopicA`:

##### HTTP Request

```http
POST http://localhost:<appPort>/TopicA
```

##### HTTP Response codes

Code | Description
---- | -----------
200  | Application has successful processed the message
503 | Application was unable to process the message, please retry (or any other failed message handling like dead letter queue, depend on the pubsub component)

##### URL Parameters

Parameter | Description
--------- | -----------
appPort | the application port

##### HTTP Response body

A JSON encoded payload.

#### Message Envelope

Dapr Pub/Sub adheres to version 0.3 of Cloud Events.

**Comment by artursouza** [comment] 2020-03-30 21:23
Hi Ricardo,

Thanks for opening this issue with such detail. This issue is related to #843. I have a few questions to clarify the actions on this.


1. GET http://localhost:<appPort>/dapr/subscribe

In this case, the only difference between 404 and any other stratus code is a warning log message, correct? We should add a `any other status` entry in the table. This way, users know that there will be a warning message.

Something like this:

Code | Description
-- | --
200 | Application subscribes to the responded topics
404 | Application does not subscribe to any topic
Others | Application does not subscribe to any topic and warning message is emitted.

2. POST http://localhost:<appPort>/TopicA

First, 204 should be an accepted success status code too (IMO).
Also, 503 is too restrictive, the retry behavior should be expected for any error code in the 500s.
In addition, we need to document the expected behavior for any other status code. I propose we log a warning and drop (no retry) any message for any status code not in the 500s or 200 or 204.

Something like this:

Code | Description
-- | --
200 or 204 | Application has successful processed the message
50x | Application was unable to process the message, to be retried.
Other | Message is dropped, warning message is emitted.

**Comment by RicardoNiepel** [comment] 2020-03-31 14:04
@yaron2 as discussed yesterday: would be awesome if we have a quick fix for 0.6.0 ready which includes:
- any response other then 200 at /[topic_name] does not return any useful information (https://github.com/dapr/dapr/blob/master/pkg/runtime/runtime.go#L944)
```res.status(500).send({ error: "hello world" })```
gives the following:
```== DAPR == time="2020-03-30T15:32:13.4326793+02:00" level=debug msg="error from app consumer: %!s(<nil>)" app_id=node-subscriber instance=XYZ scope=dapr.runtime type=log ver=edge``` - **please include status code in quick fix**
- if GET http://localhost:/dapr/subscribe returns not 200 or 404, please log it as warning

**Comment by RicardoNiepel** [comment] 2020-03-31 14:12
@artursouza 

> We should add a any other status entry in the table. This way, users know that there will be a warning message.

Perfect - LGTM

> First, 204 should be an accepted success status code too (IMO).

LGTM

> Also, 503 is too restrictive, the retry behavior should be expected for any error code in the 500s.
In addition, we need to document the expected behavior for any other status code. I propose we log a warning and drop (no retry) any message for any status code not in the 500s or 200 or 204.

Retry for all 50x is fine and correct.

The reason for introduce 503:
- the Dapr runtime - and the developer - should distinguish between:
  - the app tried to process the pubsub message but was not able to do it and want Dapr to try it again (or maybe put it into a deadletter queue)
  - the app was wrongly configured and did not received the pubsub message at all, e.g. wrong routing (404), enabled auth by mistake (401 at the topic route) or Dapr could not reach the app at all

Because 500 is the default server error - Dapr cannot distinguish between intentionally returning 500 (application wants a retry) or something really bad happened, the developer doesn't want and maybe does not recognize.
Retrying is in both situations useful, but I think we should only log these as warning, if it was unintentionally - all intentionally returns would be too much and should only be visible with debug log level.

**Comment by RicardoNiepel** [comment] 2020-03-31 20:01
@yaron2 Pls reopen, PR only partially fixed it (scope for 0.6.0)

**Comment by yaron2** [comment] 2020-03-31 20:02
Oops, Github doesn't understand "partially" :)

**Comment by yaron2** [comment] 2020-08-25 17:37
@RicardoNiepel what is needed to close this issue?

**Comment by artursouza** [comment] 2020-08-31 22:25
Based on the messages above, this is my summary of the expected behavior:

1. GET http://localhost:<appPort>/dapr/subscribe

Code | Description
-- | --
200 | Application subscribes to the responded topics
404 | Application does not subscribe to any topic
Others | Application does not subscribe to any topic and warning message is emitted.

2. POST http://localhost:<appPort>/TopicA

Code | Description
-- | --
200 or 204 | Application has successful processed the message
503 | Application chose not to process the message yet, DO NOT log warning, to be retried.
50x | Application could not process the message, DO log warning, to be retried.
Other | Message is dropped, DO log warning.

I will check the code now to see is this is the behavior implemented, if not, I will send a PR.

@RicardoNiepel  @yaron2 Agreed?

**Comment by yaron2** [comment] 2020-08-31 22:29
> Based on the messages above, this is my summary of the expected behavior:
> 
> 1. GET http://localhost:/dapr/subscribe
> 
> Code	Description
> 200	Application subscribes to the responded topics
> 404	Application does not subscribe to any topic
> Others	Application does not subscribe to any topic and warning message is emitted.
> 1. POST http://localhost:/TopicA
> 
> Code	Description
> 200 or 204	Application has successful processed the message
> 503	Application chose not to process the message yet, DO NOT log warning, to be retried.
> 50x	Application could not process the message, DO log warning, to be retried.
> Other	Message is dropped, DO log warning.
> I will check the code now to see if this is the behavior implemented, if not, I will send a PR.
> 
> @RicardoNiepel @yaron2 Agreed?

Looks good, we just need to think about how we give the gRPC API the ability to return the HTTP equivalent of `503` and `Other`.

**Comment by artursouza** [comment] 2020-09-02 21:49
Here is my proposal for GRPC:

1. For subscription via  channel.ListTopicSubscriptions()
GRPC implementation can throw an exception prior to app code or in app code, either way the existing behavior is good: log error. I recommend we change the HTTP implementation to emit Error too and not Warning, for consistency.
There is no equivalent to 404 here since users cannot choose not to implement ListTopicSubscriptions() in the GRPC callback, so there is no action item here (apart from the change in HTTP from Warning to Error - mentioned above).


2. For message delivery via clientV1.OnTopicEvent():
// Add attributes to TopicEventResponse, giving apps the chance to customize their response.
message TopicEventResponse {
  enum TopicEventStatus {
    // SUCCESS (default) is handled like 200 or 204.
    SUCCESS = 0;
    // Handled like 503. Message should be retried, no warning logged.
    RETRY = 1;
    // Just like "other" status codes: drops the message (like in success) but logs a warning. Technically users can achieve the same in the app code but offering DROP is good for consistency.
    DROP= 2;
  }

  TopicEventStatus status= 0;
}

Exceptions from clientV1.OnTopicEvent() are handled like 50x: warning is logged and message retried.

**Comment by yaron2** [comment] 2020-09-02 21:54
> For subscription via channel.ListTopicSubscriptions()
GRPC implementation can throw an exception prior to app code or in app code, either way the existing behavior is good: log error. I recommend we change the HTTP implementation to emit Error too and not Warning, for consistency.
There is no equivalent to 404 here since users cannot choose not to implement ListTopicSubscriptions() in the GRPC callback, so there is no action item here (apart from the change in HTTP from Warning to Error - mentioned above).

Agreed.

> For message delivery via clientV1.OnTopicEvent():

Agreed again. that's what I had in mind :)

This is good because typed interfaces are the gRPC way, as opposed to things that exist in HTTP like status codes but that do not have a place in the proto model.

**Comment by yaron2** [comment] 2020-09-02 22:00
HTTP part is in, by @artursouza via #1985. Keeping open until gRPC lands.

**Comment by artursouza** [comment] 2020-09-03 19:37
There has been some discussion in the PR above regarding the GRPC solution for the message delivery changes. Here is a new proposed approach where the GRPC behavior would be better aligned with the HTTP solution already merged:

For message delivery via clientV1.OnTopicEvent():

// TopicEventResponse, unchanged.
message TopicEventResponse {
}
Error status will contain error code and be parsed via `errStatus, _ := status.FromError(err)`, then the following treatment will be applied based on the status code from GRPC:
UNAVAILABLE: Application chose not to process the message yet, DO NOT log warning, to be retried.
CANCELLED, UNKNOWN, DEADLINE_EXCEEDED,  RESOURCE_EXHAUSTED, ABORTED, INTERNAL,DATA_LOSS Application could not process the message, DO log warning, to be retried.
Any other status code: Message is dropped, DO log warning.


I also propose we change the handling for HTTP too, so some 4xx error can be retriable (similar to in GRPC).

**Comment by yaron2** [comment] 2020-09-03 19:43
> There has been some discussion in the PR above regarding the GRPC solution for the message delivery changes. Here is a new proposed approach where the GRPC behavior would be better aligned with the HTTP solution already merged:
> 
> For message delivery via clientV1.OnTopicEvent():
> 
> // TopicEventResponse, unchanged.
> message TopicEventResponse {
> }
> Error status will contain error code and be parsed via `errStatus, _ := status.FromError(err)`, then the following treatment will be applied based on the status code from GRPC:
> UNAVAILABLE: Application chose not to process the message yet, DO NOT log warning, to be retried.
> CANCELLED, UNKNOWN, DEADLINE_EXCEEDED, RESOURCE_EXHAUSTED, ABORTED, INTERNAL,DATA_LOSS Application could not process the message, DO log warning, to be retried.
> Any other status code: Message is dropped, DO log warning.
> 
> I also propose we change the handling for HTTP too, so some 4xx error can be retriable (similar to in GRPC).

I strongly oppose this, as this in a gRPC programming model errors are _usually_ used to signal things to the gRPC framework and not application level errors. In the gRPC programming model, a strongly typed model is encouraged and provides better clarity.

To illustrate: A developer using gRPC with a typed model does not need to guess which error code they should return. They have an option between strongly typed options, and can infer the response just by looking at the code.
With using error codes, they are not sure which gRPC error message is the right message to convey to Dapr their intended behavior, and need to search through docs.

I suggest the following two options here:

1. Add the strongly typed options to the gRPC proto (as currently done in PR #1993) and have HTTP 1.1 continue with error status codes which are more natural to specify intent for HTTP 1.1

2. Add the equivalent of the gRPC proto fields to the response object in the HTTP response from the app.

**Comment by amanbha** [comment] 2020-09-03 20:14
I am more inclined to option 2 as stated [above](https://github.com/dapr/dapr/issues/1340#issuecomment-686717275) by @yaron2. Putting it explicit in HTTP response is more clear from user perspective rather than going through our custom interpretation of http status code.

**Comment by artursouza** [comment] 2020-09-03 21:05
Option 2 from @yaron2 has a problem of not being Restful compliant. In Restful APIs, the service uses HTTP error codes for non-successful requests. In Restful APIs, 200 (or 204) means success and no error code is expected. It means the service will need to provide a custom object for a non successful HTTP code. Then, Dapr needs to parse the body of every bad response to try to extract the custom response object. This expected behavior in HTTP is also different from GRPC. In HTTP, the custom behavior is defined in the payload of an error result while in GRPC, it is part of a successful result. But this seems to be the closest we can get to consistency between HTTP and GRPC in this scenario.

**Comment by yaron2** [comment] 2020-09-03 21:07
> Option 2 from @yaron2 has a problem of not being Restful compliant. In Restful APIs, the service uses HTTP error codes for non-successful requests. In Restful APIs, 200 (or 204) means success and no error code is expected. It means the service will need to provide a custom object for a non successful HTTP code. Then, Dapr needs to parse the body of every bad response to try to extract the custom response object. This expected behavior in HTTP is also different from GRPC. In HTTP, the custom behavior is defined in the payload of an error result while in GRPC, it is part of a successful result. But this seems to be the closest we can get to consistency between HTTP and GRPC in this scenario.

Dapr has no guarantees of being RESTFul compliant.

**Comment by artursouza** [comment] 2020-09-03 21:08
OK, then we can make option 2 and make 200 mean SUCCESS, RETRY, DROP in both GRPC and HTTP.

**Closed** 2020-09-05 04:09 UTC
Labels: P1, area/runtime/pubsub, kind/bug
