### ISSUE TITLE
The graceful-shutdown-seconds option is not forcing delay before shutdown

### ISSUE THREAD

**Issue by vlardn** [dapr/dapr#7211] opened 2023-11-17 14:26 UTC
/area runtime

## What version of Dapr?

1.12.0

## Expected Behavior

`dapr.io/graceful-shutdown-seconds` was making shutdown delay and helped to get zero downtime during the app upgrade in Kubernetes. The shutdown delay was introduced in https://github.com/dapr/dapr/pull/5562 in 2022, where the following lines were added to file `runtime.go`:
```go
log.Infof("Holding shutdown for %s to allow graceful stop of outstanding operations", duration.String())
<-time.After(duration)
```

The reason why this delay before the shutdown was implemented is described in the pull request itself https://github.com/dapr/dapr/pull/5562 and also in https://github.com/dapr/dapr/issues/5481, https://github.com/dapr/dapr/issues/4313. In particular the shutdown delay was proposed in https://github.com/dapr/dapr/issues/5481#issuecomment-1314175361:
> [yaron2](https://github.com/yaron2) Shouldn't we change the current shutdown sequence to close the HTTP/gRPC servers and app channels only after the graceful shutdown period has elapsed? (Post SIGTERM)

## Actual Behavior

Now, in the latest Dapr 1.12.0 version we don't have such delay any more for `dapr.io/graceful-shutdown-seconds` annotation and this prevents app upgrade scenarios with zero downtime on Kubernetes:

```
>  kubectl get pod backend-7dcb86877b-ctsld -n myapp-test -o yaml
...
  image: mcr.microsoft.com/daprio/daprd:1.12.0
...
 - args:
    - /daprd
    - --dapr-http-port
    - "3500"
    ...
    - --dapr-graceful-shutdown-seconds
    - "20"
  ...
```

```
time="2023-11-17T12:59:17.244381869Z" level=debug msg="Operation 1 completed with status code 200" app_id=myapp-test component="dapr-state-store (state.azure.cosmosdb/v1)" instance=backend-7dcb86877b-mczsp scope=dapr.contrib type=log ver=1.12.0
time="2023-11-17T12:59:17.799657128Z" level=info msg="Received signal 'terminated'; beginning shutdown" app_id=myapp-test instance=backend-7dcb86877b-mczsp scope=dapr.signals type=log ver=1.12.0
time="2023-11-17T12:59:17.79973723Z" level=debug msg="stopping workload cert expiry watcher" app_id=myapp-test instance=backend-7dcb86877b-mczsp scope=dapr.runtime.security type=log ver=1.12.0
time="2023-11-17T12:59:17.799900032Z" level=debug msg="disconnected from placement: rpc error: code = Canceled desc = context canceled" app_id=myapp-test instance=backend-7dcb86877b-mczsp scope=dapr.runtime.actors.placement type=log ver=1.12.0
time="2023-11-17T12:59:17.879920423Z" level=debug msg="Graceful shutdown timeout: 20s" app_id=myapp-test instance=backend-7dcb86877b-mczsp scope=dapr.concurrency.closer type=log ver=1.12.0
time="2023-11-17T12:59:17.879983024Z" level=info msg="Dapr is shutting down" app_id=myapp-test instance=backend-7dcb86877b-mczsp scope=dapr.runtime type=log ver=1.12.0
time="2023-11-17T12:59:17.880014125Z" level=info msg="Shutting down component dapr (workflow.dapr/v1)" app_id=myapp-test instance=backend-7dcb86877b-mczsp scope=dapr.runtime type=log ver=1.12.0
time="2023-11-17T12:59:17.880033125Z" level=info msg="Shutting down workflow engine" app_id=myapp-test instance=backend-7dcb86877b-mczsp scope=dapr.runtime type=log ver=1.12.0
time="2023-11-17T12:59:17.880042625Z" level=info msg="Shutting down actor" app_id=myapp-test instance=backend-7dcb86877b-mczsp scope=dapr.runtime type=log ver=1.12.0
time="2023-11-17T12:59:17.880881139Z" level=info msg="Closing HTTP server :3501…" app_id=myapp-test instance=backend-7dcb86877b-mczsp scope=dapr.runtime.http type=log ver=1.12.0
time="2023-11-17T12:59:17.88093254Z" level=info msg="Shutting down component kubernetes (secretstores.kubernetes/v1)" app_id=myapp-test instance=backend-7dcb86877b-mczsp scope=dapr.runtime type=log ver=1.12.0
time="2023-11-17T12:59:17.880997641Z" level=info msg="Shutting down component dapr-state-store (state.azure.cosmosdb/v1)" app_id=myapp-test instance=backend-7dcb86877b-mczsp scope=dapr.runtime type=log ver=1.12.0
time="2023-11-17T12:59:17.881016841Z" level=info msg="Shutting down component dapr-lock (lock.redis/v1)" app_id=myapp-test instance=backend-7dcb86877b-mczsp scope=dapr.runtime type=log ver=1.12.0
time="2023-11-17T12:59:17.881083742Z" level=info msg="Dapr runtime stopped" app_id=myapp-test instance=backend-7dcb86877b-mczsp scope=dapr.runtime type=log ver=1.12.0
time="2023-11-17T12:59:17.881115743Z" level=info msg="Closing HTTP server [::1]:3500…" app_id=myapp-test instance=backend-7dcb86877b-mczsp scope=dapr.runtime.http type=log ver=1.12.0
time="2023-11-17T12:59:17.881146443Z" level=info msg="Closing HTTP server 127.0.0.1:3500…" app_id=myapp-test instance=backend-7dcb86877b-mczsp scope=dapr.runtime.http type=log ver=1.12.0
time="2
```
As you can see from log above the Dapr exits immediately after receiving SIGTERM (i.e. without the expected 20 seconds delay).

**Comment by JoshVanL** [comment] 2023-11-17 14:36
Hi @vlardn :wave: 

This option is working as intended, i.e. configure the _maximum_ amount of time to wait before force terminating when shutting down. [From the docs](https://docs.dapr.io/reference/arguments-annotations-overview/):

```
--dapr-graceful-shutdown-seconds 	not supported 		dapr.io/graceful-shutdown-seconds 	Graceful shutdown duration in seconds for Dapr, the maximum duration before forced shutdown when waiting for all in-progress requests to complete. Defaults to 5. If you are running in Kubernetes mode, this value should not be larger than the Kubernetes termination grace period, who’s default value is 30.
```

The change in behaviour you are seeing are improvements in routine management in Dapr whereby background routines are properly tracked and waited on to close. Rather than wait a static amount of time on shutdown like before, daprd terminates as soon as all routines are closed.

What I _think_ you are asking for is a `shutdown-delay-seconds` option to add an arbitrary `time.Sleep` before executing the shutdown sequence. I'd be keen to hear what use case this serves.

**Comment by vlardn** [comment] 2023-11-17 14:49
The main use case is to achieve deployment without downtime. The problem is better described here 
https://blog.markvincze.com/graceful-termination-in-kubernetes-with-asp-net-core/
and in particular in these lines:
> The only thing we have to take care of is to make sure the container doesn’t terminate until the Endpoints of our services are updated. And the only way I could find to do this was to sleep for an arbitrary amount of time.
Since it seems that it takes around 10 seconds for the service Endpoints to get updated, we can sleep for—let’s say—20 seconds, and then with the 30 seconds default grace period that still leaves 10 seconds for the termination of the application process. 
> We can implement this sleeping either with a preStop hook: ...

PS. I personally think it's better to introduce new annotation for delay, like `dapr.io/shutdown-wait-secs` as it was proposed in https://github.com/dapr/dapr/issues/4313#issue-1155555221 but anyway the removal of shutdown delay functionality is regression and looks more like a bug.

**Comment by husseineAtBay** [comment] 2023-11-21 08:28
Hi @JoshVanL 

I think that this change is missing the point of graceful termination that worked till now, as graceful termination was the feature that helped us keep the APIs of Dapr available during pods termination and now this is just break the first behavior and I agree with @vlardn that this should be considered a regression. any idea if this is going to be discussed or handled soon?

**Comment by JoshVanL** [comment] 2023-11-21 12:13
@vlardn @husseineAtBay the docs etc. are clear that the `graceful-shutdown-grace-period` is used to set the _maximum_ time that the shutdown procedure can run for before daprd forcefully terminates itself in a destructive way. I have reopened https://github.com/dapr/dapr/issues/4313 for the feature of blocking the entire shutdown procedure for a period of time. I propose it blocks until the app reports unhealthy or `block-shutdown-seconds` seconds is reached.

I'm going to close this issue in favor of the original issue. Please add your support for that issue or feel free reopen this issue if your disagree.

**Closed by JoshVanL** 2023-11-21 12:13 UTC
Labels: kind/bug
