### ISSUE TITLE
Add published topic data for wildcard subscriptions in Pub Sub

### ISSUE THREAD

**Issue by allymparker** [dapr/dapr#1786] opened 2020-07-15 10:56 UTC
## In what area(s)?

/area runtime
## Describe the proposal

Apologies if this should be in a different repo.

It is currently possible to subscribe to wildcarded topics (where supported by the underlying technology e.g. nats), however, when the subscribed route is called the published topic information is lost.

For example, we can subscribe with:
```json
{ topic: "a.*", route: "/handler" }
```

If a message is published to `a.b` handler will be called with the payload, but the _published_ topic (`a.b`) is lost.

The proposal is to add the _published_ topic to the cloud event as an extension attribute/metadata so it can be used by the subscriber.

**Comment by yaron2** [comment] 2020-07-15 15:18
That's indeed a very good suggestion which makes sense.

/cc @LMWF @mchmarny

**Comment by mchmarny** [comment] 2020-07-15 15:48
Not sure how it works across all of the backing services but in RabbitMQ case, when subscription is made using wildcard (e.g. `a.*`) the context of the event received on subscription does include the fully qualified topic name (e.g. `a.1` or `a.2`).

If this is common for all wildcard-supporting MQs, we will need to find a valid place on CloudEvent which is passed into user code to store this data. CloudEvents v1.0 has a concept of extensions that may be worth considering (e.x. `sourcetopicname` or similar)

**Comment by yaron2** [comment] 2020-07-15 15:55
Since Dapr knows the topic that is being published to when an app publishes to it, it's easy to add the full topic name as part of the CE.

Illustration:

App 1 --> Dapr --> Subscribes to a.*

App 2 --> Dapr --> Publishes to a.b --> Dapr puts a.b in a field on the CloudEvents

Dapr --> Receives message from bus, already containing the CloudEvent with the a.b in the field --> Delivers to the app

**Comment by mchmarny** [comment] 2020-07-15 15:58
That works for events published through Dapr API. Would that approach work for when the events are published on topic NOT through Dapr API?

**Comment by yaron2** [comment] 2020-07-15 16:01
The Dapr Pub/Sub API is expected to have the user apps be the publishers and subscribers, otherwise for messages coming from external system bindings are used.

In any case, we have full coverage for the main 80% use case where Pub/Sub is used to deliver messages between the apps. For the use case you mentioned, we can try to leverage the component where possible if the event doesn't come back with the topic populated.

**Comment by allymparker** [comment] 2020-07-15 16:15
> Would that approach work for when the events are published on topic NOT through Dapr API?

I believe it would.  For example:

Dapr will subscribe to `a.*`, the underlying MQ will then pass all events with those subtopics back to Dapr from MQ whether they were published via Dapr or not.

**Comment by LMWF** [comment] 2020-07-15 21:51
Yes agree with above, it sounds useful and could be an extension in the CE.

**Comment by allymparker** [comment] 2020-07-16 07:23
I'll put a PR together with my team over the next few days to take a look at.

**Comment by allymparker** [comment] 2020-07-17 10:39
We've created a PoC where we add a topic property to the CE.  We tested it all locally using NATs and redis to ensure the behaviours were as expected, but we had a bit more of a think about it this morning and think that we could be making better use of the CE.

The `type` property is set from a constant in Dapr: https://github.com/dapr/components-contrib/blob/b16d55f8ada1302abd7261240d3d7b2c12bc2a2a/pubsub/envelope.go#L15 

Reading the [CloudEvent spec](https://github.com/cloudevents/spec/blob/v1.0/spec.md#type) and its examples, we think the `type` field could reasonably set to the published topic.  The example in the spec is `com.github.pull.create`.  Thoughts?

Also - some advice please! - we needed to change both repos to make this change, but the builds obviously fail because they are referencing the current versions.  What is the guidance on submitting changes that affect more than 1 repo?

**Comment by mchmarny** [comment] 2020-07-17 15:20
Linking relevant issue on CE v1.0 upgrade #1803 1616

**Comment by yaron2** [comment] 2020-07-17 16:53
@allymparker thanks for the PRs!

The general guideline for this is:

1. Merge PR in components-contrib
2. After components-contrib PR is merged, you run `go get -u github.com/dapr/components-contrib@master` in `dapr/dapr` to update to the latest version of contrib. The code should now build and tests should pass.

> Reading the CloudEvent spec and its examples, we think the type field could reasonably set to the published topic. The example in the spec is com.github.pull.create. Thoughts?

The issue I see here is that the `type` attribute has to be a reverse DNS, and so I don't see this naturally fitting topic names..

**Comment by mchmarny** [comment] 2020-07-17 20:53
`io.dapr.event.topic.somename` or `io.dapr.event.topic.somename.sent`?

**Comment by yaron2** [comment] 2020-07-20 16:58
I really like the approach in the current PR adding the `topic` field as an extension. I think it removes any ambiguity in that someone can inspect the payload and understand what it means without even needing to read the Dapr documentation.

**Comment by LMWF** [comment] 2020-07-21 01:14
I agree the separate field is cleaner.  In some pub/subs a dot can be in the name (a.b.c) so that may make parsing it more difficult if it were put inside the type field.

**Comment by mchmarny** [comment] 2020-07-21 15:42
The potential use of CE v1.0 extensions for the missing event context like source topic name mentioned above or things like traceID or appID which we use existing CE envelope fields for right now is outlined in #1616

**Comment by allymparker** [comment] 2020-07-22 11:59
Cool, totally happy to stick with the extension field.  What do I need to do to get these changes merged?

My only observation is that the type field isn't currently very useful from an observability perspective.

Re the CE `type` field - the [docs](https://github.com/cloudevents/spec/blob/v1.0/spec.md#type) say:

> SHOULD be **prefixed** with a reverse-DNS name
and
> The format of this is **producer defined**

My emphasis in bold. I read this to mean that the actual format doesn't matter and preferably should be prefixed with a reverse DNS.  This could make it easier to delimit/split by convention similar to @mchmarny suggestion

**Comment by mchmarny** [comment] 2020-07-22 12:25
Not sure if you had a chance to attend the community call yesterday where I went over the proposal on CE. Ideally we want avoid "re-using" any existing CE fields as that could lead to lose of user data in situation when the payload is already CE (we don't want to override the existing `type` data).  

The need to preserve the published topic name you highlighted is however important so I propose we implement this as part of the CE v1.0 upgrade work outline in #1616. 

When that lands, we'll use CE extensions to add that additional context. This way there would be explicit field for `topic` as well as a couple of other things we "squeezing" into CE like `traceid` and `appid` (see below). Would that approach work for you @allymparker?

```json
{
   "specversion": "1.0",   
   "type": "com.dapr.event.sent",
   "id": "b0ec5d2a-7d0c-40af-8e22-574768bc983c", 
   "time": "2020-07-21T07:31:00Z",
   "topic": "a.b",
   "traceid": "00-6b0b8b04cfbde34f867cc52e68eaef…",
   "appid": "my-app",     
   "source": "Dapr", 
   "data": "hello",
   "datacontenttype": "text/plain"
}
```

**Comment by allymparker** [comment] 2020-07-22 15:03
Ah sorry, missed that! Yes #1616 looks good to me.  Let me know how I can help out with (I'm more than happy to submit a pr for the v1.0 bump if that helps?)

**Comment by yaron2** [comment] 2020-07-22 15:14
We can accept and merge your PRs as it's aligned with the 1.0 plan, it doesn't need to wait until the other changes arrive.

We will review this week.

**Closed** 2020-07-22 15:48 UTC
Labels: P1, area/runtime/pubsub

**Comment by theperm** [comment] 2021-07-22 11:14
I having difficulty getting Wildcard topics to work from a .Net Core controller and I am getting no help on Discord -  i think it might be a bug but I dont know where it is. DaprD is logging the subscription as being made.

`app responded with subscriptions [{service-pubsub MyTopic.* MyTopic map[] []}]" app_id=
app is subscribed to the following topics: [MyTopic.*] through pubsub=service-pubsub" app_id=
"subscribing to topic=MyTopic.* on pubsub=service-pubsub" app_id=`

But when i publish to MyTopic.1 for example no messages are received by the controller handler configured for MyTopic. If i revert to a non-wildcard subscription and publish to MyTopic it works fine.  

Please advise on how to investigate where the problem is to figure out if this is a Dapr issue as opsed to a the .net SDK issue. There is no working example for .Net using wildcards. I think there should be.
