### ISSUE TITLE
Dapr / Actor / Reminder is keeping the state in Cosmos DB even after the reminder is inactive.

### ISSUE THREAD

**Issue by ulisesortega** [dapr/dapr#5138] opened 2022-09-06 20:29 UTC
## What version of Dapr?
1.8.0

## Deployed

The application is deployed in Azure Container App.

## Issue

I have an actor that register a reminder (CreateReminderAsync(InvoiceMessage invoice)), it's a one time Reminder, but the issue is after the reminder is trigger it keeps in Cosmos DB the state like:

`{
    "id": "InvoiceActor||F002279582||RetryReminder",
    "value": {
        "lastFiredTime": "2022-09-06T17:11:38Z",
        "repetitionLeft": -1
    },
    "isBinary": false,
    "partitionKey": "InvoiceActor||F002279582||RetryReminder",
   ........
}`

For every reminder that is inactive is keeping the state and the DB is growing. I would like to know how it can be fixed.

## Actor / Reminder Code

`public class InvoiceActor : Actor, IInvoiceActor, IRemindable
    {
        private readonly IStorageStateServiceProvider _storageStateServiceProvider;
        private readonly IBindStorageProvider _bindStorageProvider;
        private readonly IMapper _mapper;
        private readonly InvoiceSettings _invoiceSettings;
        private readonly DeadLetterSettings _deadLettersettings;
        private readonly IMonitoring<InvoiceActor> _monitoring;

        private const string RetryReminder = "RetryReminder";
        private const string InvoiceMessageStateName = "InvoiceMessageStateName";

        private IStorageStateService<Invoice> InvoiceStorageStateService => _storageStateServiceProvider.CreateStorageStateService<Invoice>(_invoiceSettings.DataStoreInvoice);
        private IStorageStateService<Customer> CustomerStorageStateService => _storageStateServiceProvider.CreateStorageStateService<Customer>(_invoiceSettings.DataStoreCustomer);
        private IBindStorage BindStorageDeadLetter => _bindStorageProvider.CreateBindStorage(_deadLettersettings.BindStorageDeadLetter, !_deadLettersettings.IsDevelopment);

        public InvoiceActor(ActorHost host,
                            IStorageStateServiceProvider storageStateServiceProvider,
                            IBindStorageProvider bindStorageProvider,
                            InvoiceSettings settings,
                            DeadLetterSettings deadLettersettings,
                            IMapper mapper,
                            IMonitoring<InvoiceActor> monitoring) : base(host)
        {
            _storageStateServiceProvider = storageStateServiceProvider;
            _bindStorageProvider = bindStorageProvider;
            _invoiceSettings = settings;
            _deadLettersettings = deadLettersettings;
            _mapper = mapper;
            _monitoring = monitoring;
        }

        public async Task ProcessInvoice(InvoiceMessage invoice)
        {
            if (invoice == null)
                return;

            this.Logger.LogInformation("Process Invoice " + invoice.InvoiceNumber);

            try
            {
                var customer = await CustomerStorageStateService.GetFromState(invoice.InvoiceAccountNumber);
                if (customer == null)
                {
                    if (invoice.RetryNumber >= _invoiceSettings.Retry)
                    {
                        await InvoiceDeadLetter(invoice);
                    }
                    else
                        await CreateReminderAsync(invoice);
                    return;
                }

                var invoiceDb = _mapper.Map<Invoice>(invoice);

                invoiceDb.CustomerId = customer.CustomerId;
                await InvoiceStorageStateService.SaveStateAsync(invoiceDb.InvoiceNumber.ToString(), invoiceDb);
            }
            catch (Exception ex)
            {
                this.Logger.LogError(ex, $"Error executing ProcessInvoice() for invoice {invoice.InvoiceNumber}");
                await _monitoring.NotifyError(ex);
                await InvoiceDeadLetter(invoice);
            }
        }

        private async Task CreateReminderAsync(InvoiceMessage invoice)
        {
            invoice.RetryNumber++;
            var reminId = Guid.NewGuid().ToString();
            invoice.RetryId = reminId;
            Logger.LogInformation($"Saving State for {invoice.InvoiceNumber} and retry {invoice.RetryNumber}");
            await SetDataAsync(invoice);

            var delatedrReminderTime = _invoiceSettings.RetryPeriodTime;
            this.Logger.LogInformation($"Create Reminder {RetryReminder} for {invoice.InvoiceNumber} in {delatedrReminderTime} => reminId : {reminId}");
            
            await RegisterReminderAsync(
               RetryReminder,
               Encoding.UTF8.GetBytes(reminId),
               TimeSpan.FromSeconds(delatedrReminderTime),
               TimeSpan.FromMilliseconds(-1));

            this.Logger.LogInformation($"Registered Reminder for {invoice.InvoiceNumber}");
        }

        public Task ReceiveReminderAsync(string reminderName, byte[] state, TimeSpan dueTime, TimeSpan period)
        {
            string reminId = Encoding.UTF8.GetString(state) ?? string.Empty;
            this.Logger.LogInformation($"ReceiveReminderAsync :: reminId => {reminId} and reminderName => {reminderName}");

            return reminderName switch
            {
                RetryReminder => RetryInvoiceMessage(),
                _ => Task.CompletedTask
            };
        }

        private async Task RetryInvoiceMessage()
        {
            try
            {
                var invoice = await GetDataAsync();
                await RemoveDataAsync();
                this.Logger.LogInformation($"Deleted State for {invoice?.InvoiceNumber} and retry {invoice?.RetryNumber}");
                if (invoice != null)
                    await ProcessInvoice(invoice);
            }
            catch (Exception ex)
            {
                this.Logger.LogError(ex, $"Error executing RetryInvoiceMessage()");
                await _monitoring.NotifyError(ex);
                await InvoiceDeadLetter(new InvoiceMessage { InvoiceNumber = this.Id.GetId() });
            }
        }

        private async Task SetDataAsync(InvoiceMessage data)
        {
            await this.StateManager.SetStateAsync(InvoiceMessageStateName, data);
        }

        private async Task<InvoiceMessage?> GetDataAsync()
        {
            var invoice = await this.StateManager.TryGetStateAsync<InvoiceMessage>(InvoiceMessageStateName);
            return invoice.HasValue ? 
                   invoice.Value : 
                   null;
        }

        private async Task<bool> RemoveDataAsync()
        {   
            return await StateManager.TryRemoveStateAsync(InvoiceMessageStateName);
        }

        protected override Task OnActivateAsync()
        {
            // Provides opportunity to perform some optional setup.
            this.Logger.LogInformation($"Activating actor id: {this.Id}");
            return Task.CompletedTask;
        }

        protected override Task OnDeactivateAsync()
        {
            // Provides Opporunity to perform optional cleanup.
            this.Logger.LogInformation($"Deactivating actor id: {this.Id}");
            return Task.CompletedTask;
        }

        private Task InvoiceDeadLetter(InvoiceMessage invoice)
        {
            this.Logger.LogError($"Adding the {invoice.InvoiceNumber} invoice in the dead letter container");
            return BindStorageDeadLetter.Create<InvoiceMessage>($"{_invoiceSettings.MSName}/{invoice.InvoiceNumber}.json", JsonConvert.SerializeObject(invoice, Formatting.Indented));
        }
    }`

**Comment by olitomlinson** [comment] 2022-09-06 20:50
@ulisesortega 

I think this may have been fixed already in the next release

https://github.com/dapr/dapr/issues/4801

**Comment by artursouza** [comment] 2022-09-09 18:46
Closing as duplicate of https://github.com/dapr/dapr/issues/4801

**Closed by artursouza** 2022-09-09 18:46 UTC
Labels: kind/bug
