### ISSUE TITLE
Please implement binary release package using Chocolatey/winget, deb & rpm 

### ISSUE THREAD

**Issue by ooeygui** [dapr/dapr#1876] opened 2020-08-07 16:13 UTC
## In what area(s)?
> /area test-and-release

## Describe the feature
We are using Dapr in a hybrid environment - where non-kubernetes nodes are connecting to a kubernetes cluster. In order to deploy to these remote endpoints on Windows and Linux, we are using Chocolatey on Windows and apt/rpm on Linux. 

Please produce and host dapr and daprd in binary packages on Chocolatey and Linux distros.

**Comment by youngbupark** [comment] 2020-08-07 16:44
cc/ @orizohar @yaron2 @yolember

**Comment by amanbha** [comment] 2020-08-07 16:52
looks like duplicate of following tracking issues for cli:
Snap for linux: https://github.com/dapr/cli/issues/173
Chocolatey for Windows: https://github.com/dapr/cli/issues/172
Winget for windows: https://github.com/dapr/cli/issues/424

**Comment by ooeygui** [comment] 2020-08-07 17:30
@amanbha, Thank you - I looked here for the issues, not on the cli. Should I resolve this one and track those?

**Comment by amanbha** [comment] 2020-08-07 18:38
> @amanbha, Thank you - I looked here for the issues, not on the cli. Should I resolve this one and track those?

@ooeygui yes, we can close this one and track the existing issues. Please add more info to the issues if needed.

**Closed** 2020-08-11 02:24 UTC
Labels: area/release-eng
