### ISSUE TITLE
Require example of openssl generated cert for bring your own cert

### ISSUE THREAD

**Issue by pzou19741** [dapr/dapr#2510] opened 2020-11-30 21:13 UTC
## In what area(s)?

I'm not able to make bring your own cert working. we use openssl to generate the cert.

Here are the steps:
openssl genrsa -out ca.key 2048
openssl req -x509 -new -nodes -key ${tmp_dir}/ca.key -sha256 -days 365 -out ca.crt -config ca.cnf -extensions v3_ca -subj /CN=Archean_CA

step certificate create cluster.local issuer.crt issuer.key --ca ca.crt --ca-key ca.key --profile intermediate-ca --not-after 8760h --no-password --insecure

> /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Release Note

RELEASE NOTE:

**Comment by pzou19741** [comment] 2020-12-08 07:04
After dump default dapr cert 

kubectl get secret dapr-trust-bundle -n dapr-system   -o json | jq '.data | map_values(@base64d)'
openssl x509 -noout -text -in ca.crt
openssl x509 -noout -text -in issuer.crt
for cert detail .
I found default cert use Signature Algorithm: ecdsa-with-SHA256. 
I checked dapr code it only support rsa and esdsa .  https://github.com/dapr/dapr/blob/master/pkg/sentry/certs/certs.go
Here is what I did but without success via openssl
1. Generate rootCA private key and cert via  modified openssl.cnf
2. generate intermediate private key cand cert
3. kubectl edit secret dapr-trust-bundle -n dapr-system to change ca.crt, issuer.crt and issuer.key
kubectl rollout restart deploy/dapr-sentry -n <DAPR_NAMESPACE>
kubectl rollout restart deploy/dapr-operator -n <DAPR_NAMESPACE>
kubectl rollout restart deploy/dapr-placement -n <DAPR_NAMESPACE>

kubectl rollout restart deploy/dapr-app -n <DAPR_APP_NAMESPACE>
but after that pod crash from time to time here is the error:"

time="2020-12-08T03:53:56.018308155Z" level=error msg="error from operator stream: rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0\"" app_id=hostnameond instance=hostname-on-79cbbc84f9-95lng scope=dapr.runtime type=log ver=0.11.3
time="2020-12-08T03:53:56.018582159Z" level=info msg="component loaded. name: kubernetes, type: secretstores.kubernetes" app_id=hostnameond instance=hostname-on-79cbbc84f9-95lng scope=dapr.runtime type=log ver=0.11.3
time="2020-12-08T03:54:01.078728859Z" level=warning msg="failed to load components: rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0\"" app_id=hostnameond instance=hostname-on-79cbbc84f9-95lng scope=dapr.runtime type=log ver=0.11.3

**Comment by mchmarny** [comment] 2020-12-08 19:27
@yaron2, do we support openssl for bring your own certs?

**Comment by yaron2** [comment] 2020-12-08 19:28
> @yaron2, do we support openssl for bring your own certs?

Yes, but the instructions need a change because of our recent SPIFFE support and a breaking change in Go 1.15 for handling certificates.

**Comment by wcs1only** [comment] 2020-12-14 23:02
Dupe of dapr/docs#1008

**Closed** 2020-12-14 23:01 UTC
Labels: P1, area/sentry
