### ISSUE TITLE
Azure container apps - Using Appconfig data in startup of application.

### ISSUE THREAD

**Issue by chielos24** [dapr/dapr#7000] opened 2023-10-05 21:06 UTC
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.11.2-msft-3

## Expected Behavior

Environment: Container Apps
dotnet core 7

Trying to set use Client AddDaprConfigurationStore() or GetConfiguration() on the builder. Also using CheckHealthAsync().
But the dapr sidecar seems to be not ready.

Log of daprd says;
`application protocol: http. waiting on port 6000.  This will block until the app is listening on that port." app_id=backoffice-api instance=backoffice-api--tgkk605-686769cfd6-w79ls scope=dapr.runtime type=log ver=1.11.2-msft-3`

My understanding is that there is a catch22. Daprd is waiting untill the app is ready. App is asking dapr sidecar for configuration data. Both are not ready.

## Actual Behavior

I know this code works, because we had this in our AKS enviroment. We are trying to switch to container apps.

## Steps to Reproduce the Problem

See above. Can share code if needed.

**Comment by yaron2** [comment] 2023-10-05 22:46
Hi @chielos24,

I think the best place to open this issue is https://github.com/microsoft/azure-container-apps/issues, especially since you mentioned this works in AKS. I'm going to close this now, but do feel free to comment here again for re-opening if you believe the issue is with Dapr upstream.

**Closed** 2023-10-05 22:46 UTC
Labels: kind/bug

**Comment by olitomlinson** [comment] 2023-10-06 23:06
@chielos24 

It might be worth trying to use the ‘WaitForSidecarAsync’ method rather than ‘CheckHealthAync’ as the wait for sidecar method doesn’t block on waiting for the app channel (via the app port) to establish, and gets around the catch 22.
