### ISSUE TITLE
Consider adding events for state updates

### ISSUE THREAD

**Issue by mkosieradzki** [dapr/dapr#697] opened 2019-10-27 10:17 UTC
It would be nice if inserting/updating/deleting something to state store would publish an event using a generic pub-sub mechanism.

The challenges arise around consistency and reliability, i.e. what if dapr sidecar/node fails after inserting but before publishing the event etc.

Several state stores are capable of emitting events in an at-least once compatible way, for such stores pub/sub binding should be configurable - what can be done by a separate mechanism.

For state stores lacking such a capability maybe a best-effort event publishing would be a good enough option? Alternatively dapr could employ some internal capabilities to add at-least once guarantee on top of state stores lacking the even emitting capabilities.

//cc: @kaluzaaa - who is considering adding search indexing capabilities to dapr

**Comment by yaron2** [comment] 2019-11-08 17:01
We have this PR targeting it:
 https://github.com/dapr/dapr/pull/719

**Comment by msfussell** [comment] 2020-09-17 22:37
Closing as a duplicate of https://github.com/dapr/dapr/issues/718

**Closed by msfussell** 2020-09-17 22:37 UTC
Labels: P2, area/runtime/state, kind/feature
