### ISSUE TITLE
When version exists in labels of Deployment, dapr may not be able to complete the creation of svc

### ISSUE THREAD

**Issue by saber-wang** [dapr/dapr#4304] opened 2022-02-28 10:43 UTC
/area operator

> 1.6.0

brief  deploy yml 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
    version: v3-1-1236
  name: test-3.1.1236
  namespace: dev
spec:
  selector:
    matchLabels:
      app: test
      version: v3-1-1236
  template:
    metadata:
      annotations:
        dapr.io/app-id: test
        dapr.io/app-port: "80"
        dapr.io/enabled: "true"
        dapr.io/http-max-request-size: "1000"
        dapr.io/log-level: debug
      labels:
        app: test
        version: v3-1-1236
    spec:
      containers:
      - image: test:v3-1-1236
```
svc yml at this time
```
#brief
apiVersion: v1
kind: Service
metadata:
  annotations:
    dapr.io/app-id:test
    prometheus.io/path: /
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
  labels:
    dapr.io/enabled: "true"
  name: test-dapr
  namespace: dev
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: test-3.1.1236
```

1.If I add a new version `Deployment`(3-1-1237)
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
    version: v3-1-1237
  name: test-3.1.1237
  namespace: dev
spec:
  selector:
    matchLabels:
      app: test
      version: v3-1-1237
  template:
    metadata:
      annotations:
        dapr.io/app-id: test
        dapr.io/app-port: "80"
        dapr.io/enabled: "true"
        dapr.io/http-max-request-size: "1000"
        dapr.io/log-level: debug
      labels:
        app: test
        version: v3-1-1237
    spec:
      containers:
      - image: test:v3-1-1237
```
2. Then delete the previous version `Deployment`(3.1.1236)
3. `test-dapr` will not be created at this time

**Comment by alberthuang24** [comment] 2022-02-28 12:30
Can you provide the operator's log? Or the actual Deployment file. I don't seem to see any annotation that starts the dapr

**Comment by saber-wang** [comment] 2022-03-01 01:01
@alberthuang24 I updated the deployment file

**Comment by alberthuang24** [comment] 2022-03-01 07:26
Okay, I think your problem is the same as mine, when the deployment changes, the service is not updated in time

https://github.com/dapr/dapr/issues/4287

**Comment by saber-wang** [comment] 2022-03-02 02:18
@alberthuang24  It should be the same problem

**Comment by yaron2** [comment] 2022-03-18 22:24
Closing as dupe of #4287.

**Closed by yaron2** 2022-03-18 22:24 UTC
Labels: kind/bug
