### ISSUE TITLE
Timer not garbage collected after actor deactivating

### ISSUE THREAD

**Issue by javageek79** [dapr/dapr#3149] opened 2021-05-10 16:13 UTC
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

1.1.x
> 1.0.x
> edge: output of `git describe --dirty`

## Expected Behavior

After a timer registration with a following period of inactivity,
timer should be garbage collected upon actor deactivation according to the configured idle time.
A timer callback should not be executed if, as shown in screenshot, after ~3 days of inactivity

## Actual Behavior

![dapr_timer_error](https://user-images.githubusercontent.com/3714921/117690255-ee997580-b1ba-11eb-8bcc-05dad8fb382b.PNG)

## Release Note

RELEASE NOTE:

**Comment by berndverst** [comment] 2021-05-12 22:29
Hello @javageek79,

From your logs I don't see `AutomationTimerActor` being activated or scheduling timers after inactivity. This appears to be a different actor called `TimerActor`.

I am assuming that these are different actors based on the different log levels and different log messages for actor activation.

I've been investigating whether it is possible for an actor to trigger a timer after deactivation. I could not force that to occur and it is not clear this is happening in your situation.

Please let me know how `TimerActor` and `AutomationTimerActor` relate to each other, if at all. It may also be helpful to have the DEBUG logs for `TimerActor` that show interaction with the DAPR API.

Thanks!

**Comment by artursouza** [comment] 2021-05-27 03:26
@javageek79  Any updates on this?

**Comment by javageek79** [comment] 2021-05-28 13:56
Hi @berndverst sorry for taking that long for a response.
`TimerActor` referes to a business object in our service. The actual dapr actor is then `AutomationTimerActor`. 
It works in a way, that per `TimerActor` a dapr `AutomationTimerActor` is instanciated and for each weekday of `TimerActor` a dapr-timer is registered that triggers once a week.

Strange thing is, that there is one activation and two deactivations of the particular actor on 5th of may (both deactivations happened in two different pods with a delay of ~12sec)
After last deactivation, there are no activities for the next two days visible in the logs regarding activation or timer execution.

I would have expected at least one activation before the publishing event on the 10th May.

I wonder, how timer lifecycle really works, as, according to https://docs.dapr.io/developing-applications/building-blocks/actors/howto-actors/#actor-timers, timer callbacks should not be executed after actor deactivation and therfore use cases in which a `delay > actor idle time` should not work, right?

**Comment by berndverst** [comment] 2021-06-01 21:30
The delay of ~12 seconds can entirely be related to the variance of the actor idle scan interval (60 seconds).

A particular timer, say `timer1` exists only once on the combination of `actorType` and `actorID`, regardless of the number of pods you have.

`delay` > `actor idle time` does work. The actor will stay activated until the `delay` has passed and then trigger the timer once. If the actor gets deactivated (based on the idle timeout setting and idle timeout scan interval setting) the timer will not trigger again automatically.

Timers are never persisted and will only trigger again after deactivation if the actor is reactivated, either by a reminder or a direct call.

@javageek79 the particular actor ID in your case was deactivated (this implies across all pods). Therefore the timer could not trigger again automatically. If you directly invoked this actor or had a reminder scheduled on this actor which would reactivate the actor, then the timer could continue to fire events according to the existing timer schedule, assuming it won't be deactivated before that time due to idle timeout.

I'm guessing what happened was this:
- Your timer had a delay of 0 (fire immediately).
- The timer was processed immediately but the method it called did not emit any logs (at least that we can see here). 
- The default actor idle timeout interval is 1 hour, so 1 hour later the actor was deactivated. Each pod may check for actor idle timeout at a slightly different time but always within the actor idle timeout scan interval. The default is `60 seconds` so this can at most deviate by 60 seconds.

Seems to be working as intended from what I can tell, assuming the timer delay was truly 0 and the immediate method invocation did indeed take place. I agree there should have been at least one - but not knowing what this timer actually calls and what kind of logging you have enabled it is impossible to further reason about this.

**Comment by berndverst** [comment] 2021-06-18 02:03
@javageek79 can we close this issue? Everything appears to be working as intended.

**Closed** 2021-08-17 22:19 UTC
Labels: kind/bug, area/runtime/actor
