### ISSUE TITLE
Publish to service bus fails with i/o timeout after a couple of ms and requires pod restart

### ISSUE THREAD

**Issue by IvanILanekassen** [dapr/dapr#4416] opened 2022-03-23 15:00 UTC
## In what area(s)?

/area runtime

## What version of Dapr?

1.6.0

## Expected Behavior

Publish operations should work flawlessly

## Actual Behavior

Some pods suddenly get into a "defunct" state when it comes to publishing messages (other pods publish messages to the same topics at the same time without any problems). The error message is on the form: `time="2022-03-16T11:37:43.267942204Z" level=debug msg="rpc error: code = Internal desc = error when publish to topic <topic> in pubsub <pubsub>: read tcp <pod ip>:<port>-><sb pe ip>:<port>: i/o timeout" app_id=<deployment> instance=<pod name> scope=dapr.runtime.grpc.api type=log ver=1.6.0`. "sb pe ip" is the Service bus private endpoint IP. Please also note that this is logged with "debug" log level. I suppose that should be changed.

One recent example is one pod that was running from 14th of March 07:17 to 16th of March 17:09. There are no logs in Dapr when messages are published successfully, but we have no reason to believe that there were any issues with publishing messages on 14th and 15th of March. Suddenly on 16th of March 12:37, we start to see the error. All publishes from the pod fails until it is deleted at 17:09. Again, we have no logs on successful publications, but our experience from live events that we have had with the same error have shown that the dapr sidecar consistently fails to publish messages until the pod is deleted. The error message speaks of an "i/o timeout", but we see in all cases that the error occurs that we get the error after 2-5ms of processing. So not much time for a timeout to occur.

This bug seems to be similar to https://github.com/dapr/dapr/issues/4031, but it has a different error message. We have reviewed the code changes in that bug but it does not seem relevant in our case since the error that we observe occurs in the Dapr sidecar and not in our container.

## Steps to Reproduce the Problem

Unclear, suddenly, some pods start to experience this error. We have two pods per deployment, and the other pod works OK, so half of the requests are failing.

## Release Note

RELEASE NOTE: **FIX** Intermittent i/o timeout error in Dapr sidecar.

**Comment by IvanILanekassen** [comment] 2022-04-04 06:29
Hi again,

Any news here? We just got the exact same issue in production,

**Comment by IvanILanekassen** [comment] 2022-04-04 12:37
As another observation, we do not see any of the errors from this code line: https://github.com/dapr/components-contrib/blob/ec5fda587ba8d54d28bbc8487dc2ed652b38b5ee/pubsub/azure/servicebus/servicebus.go#L395 (or from line 397). Moreover, we are not able to find the error message "error when publish to topic..." that we observe in our logs in the dapr-components code base (or in the dapr code base), but we do not know the code bease that well..

**Comment by IvanILanekassen** [comment] 2022-04-05 11:12
Hi again,

This problem creates lots of issues for us in production. 

We have done some more research, and we have some findings:
- Dapr is using dapr/components-contrib
- dapr-components-contrib is using github.com/Azure/azure-service-bus-go v0.10.10
- azure-service-bus-go is deprecated (Azure/azure-sdk-for-go should be used instead).
- I suppose a migration to the new SDK might need a lot of work, so I suppose this will be outside the scope of fixing this bug.
- But azure-service-bus-go has gotten some updates after 0.10.0 (current version is 0.11.5)
- Upgrading to this version in using dapr/components-contrib (and then update dapr to use the latest version of dapr/components-contrib) might be a "low hanging fruit" in this matter. 

What is the shortest path to accomplish this?

**Comment by IvanILanekassen** [comment] 2022-04-05 11:25
@yaron2 Can you assist us here? We are not that proficient in Go, so I think we need some assistance in creating an updated version of components-contrib using the latest azure-service-bus-go library.

**Comment by rogerex** [comment] 2022-04-05 22:24
Now we are 2 having this issue, we found this issue with dapr feature flag on in prod, we disabled it to avoid this issue, but we were able to reproduce it in load tests in test envs, which is good, not expert in components-contrib or go, but I can take a look, because we really want to solve this issue and use dapr for prod

**Comment by yaron2** [comment] 2022-04-05 22:54
Looking into it. cc @berndverst @ItalyPaleAle @halspang

**Comment by ItalyPaleAle** [comment] 2022-04-05 23:02
Thanks for the ping and sorry you're experiencing these issues.

Updating the SDK to the new (internally called "track2") one is in the roadmap but because it's a complete rewrite, we haven't gotten to that yet (but we will). However, because it's a complete rewrite, while it's possible that it may fix your issues, it may introduce new ones as well that we can't foresee, so it will need to be done carefully.

In the meanwhile, I can look into updating the "track1" SDK to 0.11.5, the latest one supported. Not sure if that will fix your issue, but it may be worth a shot.

Seems that what you're experiencing is a timeout that is not sent back to Dapr, so we do retry the error. I can take a look and see if there's something we can do, but if it's an issue with the SDK itself, it may just be that we need to upgrade to "track2" sooner than originally planned.

**Comment by halspang** [comment] 2022-04-05 23:04
> In the meanwhile, I can look into updating the "track1" SDK to 0.11.5, the latest one supported. Not sure if that will fix your issue, but it may be worth a shot.

We've done this in the past and found regressions. This is actually why the longhauls have a ASB test in them at all.

I have a PoC for the track2 SDK but it had a bug in it that I wasn't able to track down/haven't had time to revisit. Perhaps that time is coming up quickly :)

**Comment by yaron2** [comment] 2022-04-05 23:08
@ItalyPaleAle I looked at all the updates since our current version, and there have been multiple commits addressing reliability issues.

**Comment by yaron2** [comment] 2022-04-05 23:20
> Now we are 2 having this issue, we found this issue with dapr feature flag on in prod, we disabled it to avoid this issue, but we were able to reproduce it in load tests in test envs, which is good, not expert in components-contrib or go, but I can take a look, because we really want to solve this issue and use dapr for prod

What feature flag were you using in conjunction with the Azure Service Bus pub/sub component?

**Comment by ItalyPaleAle** [comment] 2022-04-05 23:22
@rogerex you mentioned being able to repro this in dev. Are you able to try with the 1.7 RC build and see if that makes any improvements please?

**Comment by rogerex** [comment] 2022-04-05 23:24
sure I can take a look at it, I will let you know the results

**Comment by IvanILanekassen** [comment] 2022-04-06 08:24
We observe that the logs from dapr-components are not coming to stdout in the Dapr sidecar. Is it possible to turn this log "on"? We would like to see the logs from this line: https://github.com/dapr/components-contrib/blob/1a24c8c546777b48039ef58ee2a8fcd75003f694/pubsub/azure/servicebus/servicebus.go#L395 (and also line 397). 

As a sidenote, we also observe that the logging done in this line should be error and not debug? https://github.com/dapr/dapr/blob/79ffea446dfd14ac25429c8dc9ad792983b46ce2/pkg/grpc/api.go#L324

**Comment by rogerex** [comment] 2022-04-06 20:19
So far, using 1.7 RC runtime and sdk dotnet we didn't find the issue anymore in our tests, but we will keep doing load tests this week, just let you know that we are in good path

**Comment by IvanILanekassen** [comment] 2022-04-07 11:33
@ItalyPaleAle Ref the comment above, has there been any changes to the SDK version in version 1.7 RC?

Also, we have another interesting finding from our issue in production; We have always had "a hunch" that all subsequent publishes from the pod will fail after this issue occurs, but we have not had 100% proof of this since we have not seen any logs on "successful publish". We have now added such logs in our code, and found that in some pods there are still successful publishes after this issue occurs. On closer inspection, we have found that the issue is "topic specific". 
So in one pod, we see errors on all attempts to publish to "topic1" after the issue occurs, but at the same time, all attempts to publish to "topic2" from the same pod and sidecar are successful (!)

**Comment by rogerex** [comment] 2022-04-07 20:09
Today so far we didn't find the timeout error anymore on logs, but we found another logs like: 
`time="2022-04-07T19:49:41.63877994Z" level=debug msg="{ERR_PUBSUB_PUBLISH_MESSAGE error when publish to topic dapr_xyz in pubsub pub-sub--xyz: EOF}" app_id=ir instance=abc-deployment-845c67f55f-8qx2p scope=dapr.runtime.http type=log ver=1.7.0-rc.1` 
and
`time="2022-04-07T19:48:56.56004794Z" level=debug msg="skipping status check due to error parsing result from pub/sub event 9bd125ed-c0d8-4576-9177-b7b7adc3a369" app_id=ir instance=abc-deployment-845c67f55f-8qx2p scope=dapr.runtime type=log ver=1.7.0-rc.1`

**Comment by rogerex** [comment] 2022-04-11 23:29
Update, so far timeout is not happening anymore for today, but we are getting the above issue due to a closing connection `time="2022-04-07T21:48:42.478995353Z" level=warning msg="azure service bus error: closing subscription entity for topic dapr_xyz: EOF" app_id=abc instance=abc-deployment-9bc894c66-chksp scope=dapr.contrib type=log ver=1.7.0-rc.1`
`time="2022-04-07T21:48:42.479013954Z" level=error msg="azure service bus error: error receiving message on topic dapr_xyz, EOF" app_id=abc instance=abc-deployment-9bc894c66-chksp scope=dapr.contrib type=log ver=1.7.0-rc.1`

**Comment by IvanILanekassen** [comment] 2022-04-13 08:11
Hi again,

I have two updates here: 
First, this problem was so critical for us that we decided to "short cut" the publication of messages. We are on C# and .NET core and decided to migrate to the https://www.nuget.org/packages/Azure.Messaging.ServiceBus/ package for publication. So when we publish, we are not using the DaprClient, but we are using the ServiceBus SDK instead. Luckily, this works without any problems. Based on @rogerex comment above, it seems that we have more or less the same solution as they have. 

Secondly; Before we did the switch to .NET in production we experienced a new error message (probably a separate error situation in Service bus): `time="2022-04-08T07:43:44.226415158Z" level=debug msg="rpc error: code = Internal desc = error when publish to topic <topic> in pubsub <pubsub>: the connection has been closed: Sender" app_id=<deployment> instance=<pod name> scope=dapr.runtime.grpc.api type=log ver=1.6.0`. The interesting part is that the behavior is the same; All subsequent publishes to the same topic will fail after the error first occurs (and we need a pod restart to resolve the issue).

All in all; This is a serious bug in Dapr when using Azure Service Bus. But it seems that we have solved our problems in production for now.

**Comment by artursouza** [comment] 2022-04-13 16:36
> Update, so far timeout is not happening anymore for today, but we are getting the above issue due to a closing connection `time="2022-04-07T21:48:42.478995353Z" level=warning msg="azure service bus error: closing subscription entity for topic dapr_xyz: EOF" app_id=abc instance=abc-deployment-9bc894c66-chksp scope=dapr.contrib type=log ver=1.7.0-rc.1`
> 
> `time="2022-04-07T21:48:42.479013954Z" level=error msg="azure service bus error: error receiving message on topic dapr_xyz, EOF" app_id=abc instance=abc-deployment-9bc894c66-chksp scope=dapr.contrib type=log ver=1.7.0-rc.1`

This is a warning. Does it impact publishing or subscribing?

**Comment by rogerex** [comment] 2022-04-13 20:08
Yes, the message is shown before to get `500 internal server error` when trying to publish a message (1.7 or 1.7.0-rc.1), unique solution: restart k8s deployment, I'm going to do the same as @IvanILanekassen, I will give a try to use azure service bus as publisher (not DaprClient) to send messages and use dapr as subscriber, I like dapr routing.

More context about my project: we have our message broker implementation in base of azure service bus, we never had any issue like these before, we wanted to move to dapr, thats why we created message broker V2 implementation using dapr client, thats why is easy to turn on or off dapr in our prod envs, we can reproduce many issues you have registered here in github doing load testing in our dev or stg apps.

**Comment by IvanILanekassen** [comment] 2022-04-18 07:49
@artursouza No, we have not taken the chance on upgrading to 1.7, since we have no clear repro steps/it is hard to verify if the changes we do will work or not in production.

**Comment by rogerex** [comment] 2022-04-22 14:11
We are able to reproduce this issue in an dev env without any load testing on it and frequently, checking and digging the steps for it

**Comment by yaron2** [comment] 2022-04-22 15:25
> We are able to reproduce this issue in an dev env without any load testing on it and frequently, checking and digging the steps for it

cc @artursouza @ItalyPaleAle

**Comment by ItalyPaleAle** [comment] 2022-04-22 15:32
Thanks for letting us know. I'm on vacation but I'll look at this once I'm back

**Comment by ItalyPaleAle** [comment] 2022-05-04 21:14
Wanted to share an update that work is in progress on updating the underlying SDK to the "track2" one. The PR is here: https://github.com/dapr/components-contrib/pull/1702 It needs a bit more testing before it can be merged, and it has dependencies on 2 more PRs which are currently blocked.

My hope is that we can give you a binary to test in a few days :)

**Comment by IvanILanekassen** [comment] 2022-05-05 07:51
Thanks for the update, since we primarily are experiencing this in production, I suppose we will wait for Dapr 1.8 and then try to upgrade production to see any effect.

**Comment by ItalyPaleAle** [comment] 2022-05-19 20:54
Hi all, the change is now in the master branch and will be published with 1.8. Our initial tests seem to show greatly improved performance for Azure Service Bus (both PubSub and Binding), and hopefully improved reliability too.

Would anyone be willing to help us testing this by deploying a nightly build in their test clusters?

**Comment by IvanILanekassen** [comment] 2022-05-20 15:46
Hi and thanks for the update. Do you have any instructions to how to do this in the most efficient manner? We are running on Kubernetes, using Helm and have our code in C#. Hence we might need to upgrade som NuGet packages, together with all sidecars and the Dapr control plane. We have 23 pods deployed.

**Comment by ItalyPaleAle** [comment] 2022-05-20 15:54
Hi @IvanILanekassen thanks for the response and for offering to test this in your test cluster :)

You should be able to run a nightly build of Dapr by changing the tag of the Dapr Docker image in your Helm charts. If you're using our Helm charts, that just requires changing `global.tag` to `edge` (or you can pinpoint to a specific version, such as `nightly-2022-05-19`).

Changing NuGet packages should not be required, as this is just about the Dapr control plane and sidecars. Helm should be able to do a rollout for you.

**Comment by IvanILanekassen** [comment] 2022-05-24 07:31
Hi again, 

I did a short test locally yesterday. We have a solution that uses docker-compose to run the "system locally". I bumped all the dapr images to the edge tag, and when all the container were up and running, the system did not work. I reverted to version 1.6.0 of the Dapr images, and then everything worked. I have limited time to test this, but if you have a specific nightly version tag that should work, I can do another test. Or there might be some differences in config between 16 and 1.8 that I need to remediate?

**Comment by ItalyPaleAle** [comment] 2022-05-24 13:23
Thanks for trying this. Do you have any specific detail of what the error was?

**Comment by ItalyPaleAle** [comment] 2022-05-24 14:06
I would appreciate that, please

**Comment by IvanILanekassen** [comment] 2022-05-24 18:47
Hi again, just tried this again, and it seems to work now locally. I will look into retrying this in an environment tomorrow. As I mentioned I do not have too much time to work on this, but if it is relatively easy, we'll do it.

**Comment by IvanILanekassen** [comment] 2022-06-10 16:26
Hi again,

We have now been running for two weeks with the `nightly-2022-05-24` version in one of our test environments. The environment has been running without any publish problems. I have also performed a load test processing 1000 applications and it also worked flawlessly. So it seems that this issue has been resolved in version 1.8. 

The cluster acts a bit strange, I am having problems kubectl rollout restart deployment (the new pods never leave the Pending state), and must use helm uninstall and the install later to "restart" pods. I am unsure it this is related to the Dapr version (probably not).

**Comment by ItalyPaleAle** [comment] 2022-06-10 16:45
Hi @IvanILanekassen , THANK YOU SO MUCH for testing our nightly build and confirming that Service Bus is working well for you! 🙏 And even putting it under load testing!

I think we can go ahead and close this issue, but please do let us know here (or in another issue) if you experience other problems with Service Bus.

> The cluster acts a bit strange, I am having problems kubectl rollout restart deployment (the new pods never leave the Pending state), and must use helm uninstall and the install later to "restart" pods. I am unsure it this is related to the Dapr version (probably not).

What can you see in `kubectl describe pod ...` or in other logs? If you see anything in there, care to open another issue to report that?

**Closed** 2022-06-22 03:27 UTC
Labels: kind/bug, P1, size/S, triaged/resolved
