### ISSUE TITLE
Support PostgreSQL as the configuration store

### ISSUE THREAD

**Issue by akhilac1** [dapr/dapr#4899] opened 2022-07-13 04:28 UTC
## In what area(s)?

 /area runtime

> /area operator

> /area placement

 /area docs

> /area test-and-release

### Verbatim requirement from users posted here - ###
"Configuration API as of now supported with Redis. Our primary database is YugabyteDB and hence looking for PostgreSQL support with configuration API

As of now postgreSQL is supported with state store in Dapr. We are looking for support in the configuration API as well. Currently Configuration API  supports Redis.  As of now we have Spring Config server as central server to feed other services with configuration data.  We want to use Dapr's Configuration API to achieve the same as it is inline with cloud native architecture requirements and very clean way to deploy configuration server."

## Release Note

RELEASE NOTE: **ADD** PostgreSQL supported as configuration store

**Comment by mukundansundar** [comment] 2022-07-14 04:56
duplicate of #4551

**Closed by mukundansundar** 2022-07-14 04:56 UTC
Labels: kind/enhancement
