### ISSUE TITLE
Personal suggestion: can we add event drivers or components for database operation.

### ISSUE THREAD

**Issue by SnowflyW** [dapr/dapr#1265] opened 2020-03-15 09:23 UTC
For example: monitoring MSSQL MySQL Oracle's table and view are triggered by write operations. You can input the new and old values written to dapr memory or persistent disk and DB in JSON format.

My English is not very good, the content is translated through translation software.

**Comment by msfussell** [comment] 2020-04-14 20:11
Can you explain some more? Is the scenario that you want to be notified of DB changes in your app?

**Comment by msfussell** [comment] 2020-04-14 20:12
Closing as duplicate of #718

**Closed by msfussell** 2020-04-14 20:12 UTC
Labels: triaged/unresolved
