### ISSUE TITLE
Configuration provider for Dapr

### ISSUE THREAD

**Issue by seenu433** [dapr/dapr#3497] opened 2021-07-29 13:15 UTC
Applications needs configuration and with services like Azure App Configuration, it is centralized across apps and environments. It might be beneficial to have a configuration provider abstracting the specifics products.

**Comment by daixiang0** [comment] 2021-07-30 01:40
Now we are discussing configuration API in https://discord.gg/6ScKGxYG.

**Comment by artursouza** [comment] 2021-07-30 18:56
Duplicate of #2941

**Closed by artursouza** 2021-07-30 18:56 UTC
Labels: kind/enhancement
