### ISSUE TITLE
Correlation id (traceparent) is not propagated in 0.7.0

### ISSUE THREAD

**Issue by programaka** [dapr/dapr#1533] opened 2020-05-08 03:09 UTC
## In what area(s)?
/area runtime

## What version of Dapr?
0.7.0

I have a typical pub sub scenario and using Service Bus as a message broker.
My publisher uses Dapr State Store API and Dapr Publish API and I pass correlation id (now traceparent id) to both calls so that I can track requests end-to-end in Application Insight.

In my subscriber app I extract the correlation id passed by publisher and pass it along when calling dapr output bindings.

After installing dapr 0.7.0 I am seeing 2 issues:
1. My subscriber app no longer receives correlation id from the publisher: 
` { traceparent: '00-00000000000000000000000000000000-0000000000000000-00' } `

note: traceparent looks normal in publisher app: 00-acbd9521619856c592b5971cebfb2adc-0000000000000000-01

2. In Application Insight all calls are disconnected now. It was a tree like structure before.

I changed my tracing configuration to:
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
spec:
  tracing:
    samplingRate: "1"
```

Also renamed "x-correlation-id" to "traceparent" everywhere in my apps and cleaned the Service Bus queue. Anything else I am missing?

**Comment by yaron2** [comment] 2020-05-08 03:11
@shalabhms @youngbupark can you assist?

**Comment by youngbupark** [comment] 2020-05-08 03:45
@programaka Sorry for breaking your scenario! We will investigate it about what we missed. Can you please share the screenshot of app map in application insights?

**Comment by yaron2** [comment] 2020-05-08 04:33
If this is correct, it's a P0.

**Comment by programaka** [comment] 2020-05-08 06:58
@youngbupark 

now:
![map_now](https://user-images.githubusercontent.com/12563022/81379600-412ee600-90be-11ea-85ea-793cdaca8efc.JPG)

before:
![map_used_to_be](https://user-images.githubusercontent.com/12563022/81379631-4ee46b80-90be-11ea-86f6-d88d84b93265.JPG)

End-to-end transaction view (now):
![end-to-end-transaction-actual](https://user-images.githubusercontent.com/12563022/81379674-64f22c00-90be-11ea-9948-356f9bed207f.JPG)

End-to-end transaction view (before):
![end-to-end-transaction-expected](https://user-images.githubusercontent.com/12563022/81379703-70455780-90be-11ea-94d2-80ff017922b1.JPG)

**Comment by youngbupark** [comment] 2020-05-09 17:43
@programaka Thanks for the report. We have changed the behavior in 0.7.0, but this is not what we expected.

@shalabhms Unfortunately, new code doesn't extract trace id from cloudevent payload so that @programaka found zeros trace/span ids. I remembered that we decided to create the dependency node for pubsub component, but it doesn't seems like it works as we decided--publish and subscribe dependencies are supposed to be same and trace id should not be zeros trace/span ids. 

The old way that @programaka shared makes more sense. We can treat pubsub as a normal service invocation. state/binding can be treat it as normal dependency node. Can we write up small proposal for state/binding/pubsub for http and grpc scenarios ? Also we have to provide good documentation for distributed trace for each components. Instead of rushing out fix the problem, I suggest to fix this with proposal and good documentation in 0.8.0 release.

cc/ @yaron2 @amanbha @msfussell @orizohar

**Comment by yaron2** [comment] 2020-05-09 18:20
Since this is a regression, I would say this is a P0 and should be released as 0.7.1.

**Comment by youngbupark** [comment] 2020-05-09 18:50
> Since this is a regression, I would say this is a P0 and should be released as 0.7.1.

Yup, make sense. Pubsub part is easy to fix; extracting correlation id from cloudevent payload.

**Comment by yaron2** [comment] 2020-05-09 18:55
> > Since this is a regression, I would say this is a P0 and should be released as 0.7.1.
> 
> Yup, make sense. Pubsub part is easy to fix; extracting correlation id from cloudevent payload.

Yeah. We need to fix this and the binding event, and release docs about how to propogate the context (which should be the same for invocation/pubsub/state/bindings) and extracting the context in user code for invocation/pubsub/binding

**Comment by msfussell** [comment] 2020-05-09 20:34
Agreed on getting this fixed in a 7.1 release and especially have docs on how to propogate the context across different calls.

**Comment by youngbupark** [comment] 2020-05-09 23:24
Agree to fix  Pubsub in 0.7.1, 

We will refactor tracing code soon for next milstone. I do recommend to change bindings and state behavior with the docs and samples in the next milestone. The previous tracing for binding and state was wrong because we expose internal localhost communication. we need to find a way to hide localhost communication and show proper dependency tracing. That’s why I suggest to write Small proposal first. 

Also we need to have a proper change in dotnet sdk and java sdk which allows user to pass their own correlation headers in a seamless way. 

In sum, here is my suggestion:

1. Change pubsub in 0.7.1 - populate missing trace id to subscriber app
2. Write small proposal for binding and state first and then implement it with tracing Code refactoring for 0.8.0 release
3. Write docs, samples, and sdks in 0.8.0 release

@yaron2 @msfussell any feedbacks?

**Comment by youngbupark** [comment] 2020-05-09 23:26
@shalabhms ^

**Comment by yaron2** [comment] 2020-05-09 23:29
> Agree to fix Pubsub in 0.7.1, but not for the others, state and bindings.
> 
> We will refactor tracing code soon for next milstone. I do recommend to change bindings and state behavior with the docs and samples in the next milestone. The 0.6.0 tracing for binding and state was wrong because we exposed internal localhost communication. we need to find a way to hide localhost communication and show proper dependency tracing. That’s why I suggest to write Small proposal first.
> 
> Also we need to have a proper change in dotnet sdk and java sdk which allows user to pass their own correlation headers in a seamless way.
> 
> In sum, here is my suggestion:
> 
> 1. Change pubsub in 0.7.1 - populate missing trace id to subscriber app
> 2. Write small proposal for binding and state first and then implement it with tracing Code refactoring for 0.8.0 release
> 3. Write docs, samples, and sdks in 0.8.0 release
> 
> @yaron2 @msfussell any feedbacks?

lgtm. I'm ok with this because state can still be traced today. The details of how it looks on the map is ok to change for 0.8.

**Comment by shalabhms** [comment] 2020-05-11 17:49
Looking at the issue . Thanks.

**Comment by shalabhms** [comment] 2020-05-11 17:55
I think the fix is this PR https://github.com/dapr/dapr/pull/1482 .

cc @yaron2 , @youngbupark , @amanbha

**Comment by shalabhms** [comment] 2020-05-12 22:20
This issue is fixed through https://github.com/dapr/dapr/pull/1544

**Closed by shalabhms** 2020-05-12 22:20 UTC
Labels: P0, kind/bug
