### ISSUE TITLE
jsoniter.Unmarshal deserialization int64 lose precision

### ISSUE THREAD

**Issue by loyldg** [dapr/dapr#4026] opened 2021-12-14 04:13 UTC
## In what area(s)?

> /area runtime

dapr use jsoniter.Unmarshal to decode json string,
when decode int64 value (greather than 2^52) into map[string]interface{} ,it will decode int64 as float64,and will lose precision.
## What version of Dapr?

> 1.5.1
## Expected Behavior

pubsub:The subscriber receive the same data as published
```c#
public class Transaction
{
    public string Id { get; set; }
    public long TestLongId { get; set; }
}

var data = new Transaction
{
    Id = "test id",
    TestLongId = 1223372036854775811
};
```

## Actual Behavior

The subscriber received data is
```c#
{
    Id = "test id",
    TestLongId = 1223372036854775808
}
```

## Steps to Reproduce the Problem

1.run pubsub subscriber

2.publish data contains int64 value(greather than 2^52),then check received data whether the same with the published data

## Release Note

RELEASE NOTE:

**FIX** Bug in runtime.

**FIX** Bug in pubsub.

**Comment by real-zony** [comment] 2021-12-15 14:56
This issue is the same as [https://github.com/dapr/dapr/issues/3837](https://github.com/dapr/dapr/issues/3837).
I think it is caused by the JSON deserialization. [https://github.com/square/go-jose/issues/351](https://github.com/square/go-jose/issues/351)

**Comment by yaron2** [comment] 2021-12-20 03:10
Closing as dupe of #3837

**Closed by yaron2** 2021-12-20 03:10 UTC
Labels: kind/bug
