### ISSUE TITLE
Dapr Publish to Topic failing - requires restart of contaienr

### ISSUE THREAD

**Issue by R-Lamberson** [dapr/dapr#4031] opened 2021-12-14 20:37 UTC
## In what area(s)?

In the dapr runtime 

## What version of Dapr?

using  1.2.x

## Expected Behavior

We have a .net core service worker process that is publishing messages to an Azure service bus Topic.   Expectation is that this will run stabily without user intervention

## Actual Behavior

The service worker process runs stabiliy for periods of time but will encounter the following error which requires the entire process to be restarted to clear the issue.   

```
2021-12-14T15:01:16.627319300Z       System.AggregateException: One or more errors occurred. (Publish operation failed: the Dapr endpoint indicated a failure. See InnerException for details.)
2021-12-14T15:01:16.627319300Z        ---> Dapr.DaprException: Publish operation failed: the Dapr endpoint indicated a failure. See InnerException for details.
2021-12-14T15:01:16.627319300Z        ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="error when publish to topic XXXX/XXXXX/XXXX/XX in pubsub azure.servicebus.XXXX.XXXXX: read tcp 10.10.2.192:49258->xx.xx.xxx.xx:5671: wsarecv: An existing connection was forcibly closed by the remote host.")
```

## Steps to Reproduce the Problem

This is likely environment specific

## Question

The dapr client is dependency injected in the c# .net core project via the services.AddDapr.   Is there a callback mechanism or grpcchanneloptions property that can reset the connection status of the dapr client so that the entire process/contaienr does not have to be restarted

**Comment by R-Lamberson** [comment] 2022-01-07 14:14
Upgraded to 1.5.1 runtime and client however still seeing sporadic failures related to publishing 

Publish operation failed: the Dapr endpoint indicated a failure. See InnerException for details. Status(StatusCode="Internal", Detail="error when publish to topic external/####/#########/in in pubsub azure.servicebus.core.system: read tcp 10.0.4.15:33334->40.84.185.67:5671: read: connection reset by peer"

Grpc.Core.RpcException at Dapr.Client.DaprClientGrpc+<MakePublishRequest>d__17.MoveNext

Dapr.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=a686d5d635c0f0e6

note: #s are blanked out sensitive info not actual characters

**Comment by jjcollinge** [comment] 2022-01-07 15:02
Thanks for the update @R-Lamberson. @pkedy I was just looking at our [existing recovery logic in the ASB publish method](https://github.com/dapr/components-contrib/blob/ab91ae1aa49b7efff5a9590dd1722668c9f7e686/pubsub/azure/servicebus/servicebus.go#L371). Currently we retry on an connection closed error but we don't actually recreate the connection (`sender`). I think on `connClosedError` we should create a new connection and update the `a.topics` map before retrying, WDYT?

**Comment by jjcollinge** [comment] 2022-01-08 14:07
Actually I was mistaken on how the SDK handled this. Looks like [`Topic.Send(...)`](https://github.com/Azure/azure-service-bus-go/blob/a14e023504e9dadda9b2ca6458e62bb9ace81ef6/topic.go#L96) actually does create a new connection, session and link on each call so the cache shouldn't be causing an issue.

**Comment by R-Lamberson** [comment] 2022-01-18 22:10
@jjcollinge I have resolved the errors that were occurring 
1) implemented the daprClientBuilder using dependency injection and modified the areas where the daprClient was being used to wrap the instantiation of the daprClient as part of using to make sure the any unmanaged resources were being released.  This cleared a substantial number of the original issues 

<img width="484" alt="image" src="https://user-images.githubusercontent.com/48865653/150025777-2d403a3a-68f5-43e1-8fe0-f15e26dd5198.png">

2) second added the following grpc configuration to the dapr client builder configuration which appears to have the cleared the rest of the errors.  The default timeouts should be looked at as there seems to be some conflict.

<img width="238" alt="image" src="https://user-images.githubusercontent.com/48865653/150026017-125aaf9c-bedc-4f3b-a2c1-4b7001982d20.png">

**Comment by rogerex** [comment] 2022-04-05 22:21
I have this issue too, I'm not understanding very well the issue, I didn't know either that dapr client was using grpc options
but I can reproduce the issue doing load testing, in my case I'm using my own client calling a http client `new Uri($"http://localhost:3500/v1.0/publish/{DaprComponentsConstants.ComponentPubSubName}/{topic}" + queryUrlParams);` due to custom cloud event properties
The error is quite the same `time="2022-04-05T21:08:36.679570572Z" level=debug msg="{ERR_PUBSUB_PUBLISH_MESSAGE error when publish to topic XXXX in pubsub pub-sub--xyz: read tcp XY.XYZ.X.144:51518->XYZ.XY.XYZ.205:5671: i/o timeout}" app_id=ir instance=my-xyz-deployment-84f7d4d9b6-kcx7l scope=dapr.runtime.http type=log ver=1.6.1`

**Comment by R-Lamberson** [comment] 2022-04-06 16:44
I am reopening this item as we still see this issue in our environments (production and development) and while adding the grpc options seems to help this still occurs and causing support issues to manage resending of messages.   Very similar logging associated to what @rogerex  reported above with regards to the underlying failure being an i/o timeout.

**Comment by scano12** [comment] 2022-05-26 13:00
Has there been any movement on this issue that we know? This is also causing an intermittent issue from time to time in our prod env.

**Comment by artursouza** [comment] 2022-08-01 16:29
Does this issue still happen in 1.8? Also, which components are affected?

**Comment by R-Lamberson** [comment] 2022-11-15 20:22
So I have just been able to upgrade our dev and prod environments to 1.9.3 and will see if this helps the stability problem.

**Comment by R-Lamberson** [comment] 2022-12-13 18:03
@artursouza So not stabilized yet with the upgrade to 1.9.3 however seeing a different set of errors than before

I am seeing the following message in our log captures however not certain what exactly means 

*Error{Condition: amqp:not-allowed, Description: A link to connection '22605156' $cbs node has already been opened., Info: map[]}

**Comment by yaron2** [comment] 2023-02-01 20:55
@R-Lamberson there have been many changes to the component for 1.10 - please try this again with 1.10 and report back if the issue persists. closing for now.

**Closed by yaron2** 2023-02-01 20:55 UTC
Labels: kind/bug, P1, size/S, triaged/resolved
