### ISSUE TITLE
[E2E Test] Sidecar injection delay

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#3026] opened 2021-04-06 05:24 UTC
This error is frequently seen on Windows runs and sometimes on Linux runs too:

![image](https://user-images.githubusercontent.com/130954/113662779-9e7c4000-965d-11eb-9148-5dcfeb303c9d.png)

![image](https://user-images.githubusercontent.com/130954/113662794-a4722100-965d-11eb-9689-c879c124cd52.png)

**Comment by wcs1only** [comment] 2021-05-17 20:59
There were two root causes here. One of them is fixed in #3139, the other should be fixed by the same root cause as some of the other test failures we've had on Windows. Namely, TCP connections within the cluster are getting randomly reset, including inbound connections to the sidecar injector from kubernetes.

**Comment by wcs1only** [comment] 2021-05-17 21:00
I had closed this, but on second thought, I should leave it open until we get a resolution on the TCP connection issue. Either by it being fixed upstream, or by having kubernetes retry reset connections (if that is possible).

**Comment by wcs1only** [comment] 2021-05-20 16:51
No since of this since we deployed the windows container networking fix. Closing.

**Closed by wcs1only** 2021-05-20 16:51 UTC
Labels: P1, area/test/e2e, kind/bug
