### ISSUE TITLE
Block cross Pods calls to Dapr sidecar

### ISSUE THREAD

**Issue by cmendible** [dapr/dapr#2914] opened 2021-03-11 14:50 UTC
## In what area(s)?

/area runtime

## Update

An app can call a sidecar from another POD, even when the app is different. This should not be allowed.

## Original

Add a filter to the secret API so it only responds to internal calls.

Using API tokens and Network Policies is helpful securing the endpoint but implementing a filter will ensure that the secrets are only available to the application inside the pod reducing possible attack surface.

The filter could be implemented with code similar to the following:

``` golang
        allowed := false
	remoteIP, _, _ := net.SplitHostPort(r.RemoteAddr)
	if remoteIP == "::1" || remoteIP == "127.0.0.1" {
		allowed = true
	}
	if !allowed {
		//show simple forbidden text
		log.Printf("blocked %s", remoteIP)
		http.Error(w, http.StatusText(http.StatusForbidden), http.StatusForbidden)
		return
	}
```

There was a small conversation on the topic [here](https://discord.com/channels/778680217417809931/781589820128493598/805857248609697833)

**Comment by artursouza** [comment] 2021-06-07 22:17
Dapr only listens on localhost today. What is the scenario this will resolve?

**Comment by cmendible** [comment] 2021-06-08 07:43
@artursouza at the present it's possible to call the secrets endpoint form another pod in the cluster. The idea is to reject any invocation of the secrets endpoint that comes from outside the pod, reducing the attack surface.

**Comment by wcs1only** [comment] 2021-06-10 00:04
> @artursouza at the present it's possible to call the secrets endpoint form another pod in the cluster. The idea is to reject any invocation of the secrets endpoint that comes from outside the pod, reducing the attack surface.

Can you give an example of this? This should not be possible, and if it is I'm not sure your suggestion would fix/change anything, given that we only listen on localhost already.

**Comment by wcs1only** [comment] 2021-06-10 01:01
> > @artursouza at the present it's possible to call the secrets endpoint form another pod in the cluster. The idea is to reject any invocation of the secrets endpoint that comes from outside the pod, reducing the attack surface.
> 
> Can you give an example of this? This should not be possible, and if it is I'm not sure your suggestion would fix/change anything, given that we only listen on localhost already.

Ok, I just tried this, and you're right this is totally allowed. I have some broken assumptions I need to track down.

**Comment by artursouza** [comment] 2021-06-10 05:45
> > > @artursouza at the present it's possible to call the secrets endpoint form another pod in the cluster. The idea is to reject any invocation of the secrets endpoint that comes from outside the pod, reducing the attack surface.
> > 
> > 
> > Can you give an example of this? This should not be possible, and if it is I'm not sure your suggestion would fix/change anything, given that we only listen on localhost already.
> 
> Ok, I just tried this, and you're right this is totally allowed. I have some broken assumptions I need to track down.

Thanks Charlie for tracking this down. We must close this door.

**Comment by cmendible** [comment] 2021-06-11 10:34
> > @artursouza at the present it's possible to call the secrets endpoint form another pod in the cluster. The idea is to reject any invocation of the secrets endpoint that comes from outside the pod, reducing the attack surface.
> 
> Can you give an example of this? This should not be possible, and if it is I'm not sure your suggestion would fix/change anything, given that we only listen on localhost already.

Hi, what I attempt to suggest is a filter to verify that the caller is indeed inside the pod or an allowed list, which is different from the fact that Dapr listens on localhost.

**Comment by artursouza** [comment] 2021-06-13 22:14
> > > @artursouza at the present it's possible to call the secrets endpoint form another pod in the cluster. The idea is to reject any invocation of the secrets endpoint that comes from outside the pod, reducing the attack surface.
> > 
> > 
> > Can you give an example of this? This should not be possible, and if it is I'm not sure your suggestion would fix/change anything, given that we only listen on localhost already.
> 
> Hi, what I attempt to suggest is a filter to verify that the caller is indeed inside the pod or an allowed list, which is different from the fact that Dapr listens on localhost.

Charlie is looking into that. If Dapr only listens to localhost and not exposed to other PODs, then the filter would be redundant.

**Comment by wcs1only** [comment] 2021-07-22 23:13
Reopening for 1.4, we had to revert this due to a performance regression introduced by the new healthcheck type.

**Comment by daixiang0** [comment] 2021-08-24 02:36
Any process for it @pkedy?

**Closed** 2021-09-01 22:19 UTC
Labels: kind/feature, question, P1, size/S, size/XS, triaged/resolved
