### ISSUE TITLE
Querying the state does not work in Azure Containers App

### ISSUE THREAD

**Issue by sergiibielskyi** [dapr/dapr#4459] opened 2022-03-31 09:26 UTC
Hi team, 
I am trying to find the solution to how to get results from state storage by using a specific query, not just getting item by id. I found a good explanation here https://docs.dapr.io/developing-applications/building-blocks/state-management/howto-state-query-api/. And I prepared method to use query state.

CancellationTokenSource source = new CancellationTokenSource();
CancellationToken cancellationToken = source.Token;
        
        var query = "{" +
                "\"filter\": {" +
                    "\"EQ\": { \"value.style\": \""+ style +"\" }" +
                "}" +
            "}";
        
 var queryResponse =  await daprClient.QueryStateAsync<ObjectModel>(storeName, query, cancellationToken: cancellationToken);

Locally, it works. But when I try to publish that into the Azure Containers App I see 500 error and any description why it happens.

I assume, probably Azure Containers App service doesn't have the right Dapr runtime but I can not prove it.
Any ideas?

**Comment by sergiibielskyi** [comment] 2022-03-31 09:40
Update. Found an error into app logs
Dapr.DaprException: Query state operation failed: the Dapr endpointed indicated a failure. 
See InnerException for details.  ---> Grpc.Core.RpcException: Status(StatusCode="Unknown", 
Detail="cannot proxy request: missing dapr-app-id metadata")    
at Dapr.Client.DaprClientGrpc.QueryStateAsync[TValue](String storeName, String jsonQuery,
 IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)    --- 
 End of inner exception stack trace ---    
 at Dapr.Client.DaprClientGrpc.QueryStateAsync[TValue](String storeName, 
 String jsonQuery, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)    
 at mart.cosmosdb.ObjectController.GetObjectsByQuery(String style) 
 in /cosmosdb/mart-api-cosmos-db/Controllers/ObjectController.cs:line 38   
  at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.
  TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, 
  ObjectMethodExecutor executor, Object controller, Object[] arguments)    
  at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.
  <InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    
  at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.
  <InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, 
  Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    
  at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by torosent** [comment] 2022-03-31 16:15
Hi @sergiibielskyi , Can you reference this issue here https://github.com/microsoft/azure-container-apps/issues?
We will take a look.

**Comment by yaron2** [comment] 2022-03-31 16:27
Thanks @sergiibielskyi, closing this as this belongs to the container apps GitHub repository.

**Closed by yaron2** 2022-03-31 16:27 UTC
Labels: kind/bug

**Comment by sergiibielskyi** [comment] 2022-03-31 18:37
> Hi @sergiibielskyi , Can you reference this issue here https://github.com/microsoft/azure-container-apps/issues? We will take a look.

did not find. Thanks.

**Comment by k33lan** [comment] 2022-04-28 13:50
Hi, did you find a solution to this issue? I've gotten this error, but ONLY for querying. Everything else is fine.

**Comment by yaron2** [comment] 2022-04-28 13:55
> Hi, did you find a solution to this issue? I've gotten this error, but ONLY for querying. Everything else is fine.

Azure Container Apps uses Dapr 1.4 which doesn't support querying. I know they're going to upgrade to 1.7 soon. cc @torosent

**Comment by k33lan** [comment] 2022-04-28 13:56
Ah, that makes perfect sense. Wish I'd have asked this question a few days ago.

Many thanks for the info!

**Comment by tjoudeh** [comment] 2022-08-12 02:35
The problem is still there even though they are Container Apps use v1.7.3. I can't query Cosmos DB store when deploying to container apps, while query cosmos db works when I self-host dap on my machine with no issues.

This is the exception I'm receiving 

```
Dapr.DaprException: Query state operation failed: the Dapr endpointed indicated a failure. See InnerException for details.
 ---> Grpc.Core.RpcException: Status(StatusCode="Unimplemented", Detail="Not Implemented")
 at Dapr.Client.DaprClientGrpc.QueryStateAsync[TValue](String storeName, String jsonQuery, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)
 --- End of inner exception stack trace ---
```

![image](https://user-images.githubusercontent.com/3114431/184274259-e6392f29-4c13-40d2-a312-2f0167526efc.png)
FYI @yaron2 @torosent if you have any input here

**Comment by yaron2** [comment] 2022-08-12 03:42
This needs to be tracked here: https://github.com/microsoft/azure-container-apps/issues/155

**Comment by akshat172** [comment] 2022-08-22 01:07
The issue is still there 
![image](https://user-images.githubusercontent.com/26165605/185820067-34068b40-a6c2-4e3d-be76-d7955f6583a1.png)
![image](https://user-images.githubusercontent.com/26165605/185820116-64077687-562c-4ce8-a501-426f7a9ce3a5.png)

**Comment by akshat172** [comment] 2022-08-22 01:07
Any updates on the fix
