### ISSUE TITLE
Dapr Duplicates Headers

### ISSUE THREAD

**Issue by Admiralkheir** [dapr/dapr#7475] opened 2024-02-01 16:18 UTC
## In what area(s)?
/area runtime

## What version of Dapr?
> 1.11.2 to 1.12.4

## Expected Behavior
dapr should forward headers without modify them

## Actual Behavior
After updating dapr to version 1.12.4, headers are duplicated when a 404 or 500 status code is returned by the application. This situation does not exist in version 1.11.2
![dapr-bug](https://github.com/dapr/dapr/assets/22660149/41be4a9b-1fa0-4067-a8e3-4b41f2a3fcae)

## Steps to Reproduce the Problem
1. Create simple app returned to 404 status code
2. Upgrade dapr to version 1.12.4
3. Start dapr sidecar and app on local
4. send request to sidecar

**Comment by yaron2** [comment] 2024-02-01 17:11
Duplicate of https://github.com/dapr/dapr/issues/7434.

This was fixed and will be released in the upcoming 1.13 release.

**Closed by yaron2** 2024-02-01 17:11 UTC
Labels: kind/bug
