### ISSUE TITLE
Memory consumption problem using Workflow in daprd. V1.14.1. OOMKilled

### ISSUE THREAD

**Issue by arturotrenard** [dapr/dapr#8041] opened 2024-09-02 14:15 UTC
## In what area(s)?
Dapr Workflow

> /area runtime
SDK .Net V1.14

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?
V1.14.1

## Actual Behavior

I am currently experiencing a progressive memory consumption in daprd. Until reaching the maximum consumption of the pod. And causing the pod to reboot. This started happening immediately after the upgrade we did. We were using version V1.13.5 and we moved to v1.14.1. We didn't make any code improvements, we just updated the version of the nugets for .NET. And we did not use the new scheduled reminder preview feature. 
To the level of having OOMKilled. I am using postgresql to persist state and the workflow is very simple a monitor reusing key. And it receives external event. Every 10 sec. Before the upgrade it only occupied 57.4mb and now it consumes all the allocated memory.

![Screenshot from 2024-09-02 16-09-25](https://github.com/user-attachments/assets/eb381c22-5c21-46c1-ad13-c7993a139a30)
![Screenshot from 2024-09-02 16-14-57](https://github.com/user-attachments/assets/988aa690-b174-455e-bdea-750f6cb365a3)

**Comment by yaron2** [comment] 2024-09-02 14:42
Looking into it. Please ping me on Discord in case we need further details like a memory dump, my handle's `yaron2`.

**Comment by mikeee** [comment] 2024-09-03 19:04
Duplicate of - https://github.com/dapr/dapr/issues/7777 which has been added to tracking for v1.15

**Comment by yaron2** [comment] 2024-09-03 19:05
Closing as dupe

**Comment by yaron2** [comment] 2024-09-03 19:06
@mikeee #7777 will be released as part of 1.14.2

**Closed by yaron2** 2024-09-03 19:05 UTC
Labels: kind/bug, P0
