### ISSUE TITLE
v1.0 Milestone 4 Plan

### ISSUE THREAD

**Issue by msfussell** [dapr/dapr#2347] opened 2020-10-28 22:57 UTC
*Milestone Lead:* 
*Milestone Buddy:*  

## Deliverables for this milestone 

* [ ] Release v1.0-rc4 
* [ ] Addressed customer feedback from previous RC
* [ ] Documentation complete
* [ ] Samples and quickstarts complete
* [ ] "Getting Started" usability review complete
* [ ] GTM plan activities complete

**Starts - 9th Jan 2021** 
**Endgame starts - 25th Jan 2021** 
**Release date - 28th Jan 2021**

**Comment by yaron2** [comment] 2021-02-16 18:01
Dupe of endgame

**Closed by yaron2** 2021-02-16 18:01 UTC
