### ISSUE TITLE
Create manifest for winget

### ISSUE THREAD

**Issue by spboyer** [dapr/dapr#2944] opened 2021-03-17 18:10 UTC
Create a manifest -> https://github.com/microsoft/winget-pkgs/blob/master/README.md#authoring-a-manifest

Should support `winget install dapr` (or proper moniker)

@markrussinovich

**Comment by artursouza** [comment] 2021-03-19 06:50
Duplicate of https://github.com/dapr/cli/issues/424

**Closed by artursouza** 2021-03-19 06:50 UTC
