### ISSUE TITLE
[Proposal] Simplify tracing configuration and resolve the potential exporting bug

### ISSUE THREAD

**Issue by youngbupark** [dapr/dapr#1317] opened 2020-03-25 17:58 UTC
## In what area(s)?

/area runtime

## Goals

- [x] Remove `expandParams` and `includeBody` to simplify tracing options and remove potential bugs
- [x] Use tracing sampler and Simplify tracing onboarding experience

## Problem

In order to enable tracing, we need to do three steps:

1. Apply tracing config
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
spec:
  tracing:
    enabled: true
    expandParams: false
    includeBody: true
```
2. Apply tracing component yaml
3. Add dapr.io/tracing annotation to each app

This proposal addresses the issue of tracing config. Dapr provides three options: enabled, expandParams, and includeBody.

* `enabled` options is to enable tracing globally; even if app needs to configure annotation
* `expandParams` option exports all headers of http or grpc into trace span's annotation and 
* `includeBody` option exports request body into trace span's annotation.

If users passes non-utf8 characters and 512+ character body or header values, opencensus exporter fails to export trace span to the telemetry backend (such as zipkin, ocagent, etc) without any verbosed error because:
```
Opencensus trace allows only utf-8 512 characters for span annotation.
```
In this cases, all trace spans in the buffer will be discarded silently (see the [issue](https://github.com/dapr/dapr/pull/1305)). User could disable `expandParams` and `includeBody` as a workaround but, this will not be the right fix. 

## Benefit of opencensus trace sampler

The [standard correlation headers](https://www.w3.org/TR/trace-context/#traceparent-header) include four fields:  version, trace-id, parent-id, trace-flags

examples:
```
Value = 00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01
base16(version) = 00
base16(trace-id) = 4bf92f3577b34da6a3ce929d0e0e4736
base16(parent-id) = 00f067aa0ba902b7
base16(trace-flags) = 01  // sampled
```

To understand how sampler works, assume AppA has 1.0 rate and AppB has 0.0 rate. According to [W3C spec](https://www.w3.org/TR/trace-context/#traceparent-header)--opencensus follows W3C standard--, AppA needs to pass standard correlation headers to AppB. 

The sampling rate between AppA and AppB is different.

but opencensus sdk in AppB looks at parent span (AppA's span) trace-flags. If parent span is sampled, AppB's span will be sampled. In this case, AppB's span will be sampled even if sample rate is 0
 
[Open census sampling code](https://github.com/census-instrumentation/opencensus-go/blob/46dfec7deb6e8c5d4a46f355c0da7c6d6dc59ba4/trace/sampling.go#L52-L54)

## Proposal

The proposal simplifies the tracing config option and deliver the correct functional features.

### Simplified tracing config

* Default behavior: daprd enables tracing with low tracing sampling rate by default
* Remove `expandParams` and `includeBody` options
   - spanAnnotation value must be UTF-8 charset and shorter than 512 characters. 
   - populating all headers for HTTP and gRPC requests to span annotation exposes to the potential security and PII information violation. 
* Introduce `samplingRate` option to leverage opencensus [probabilitstic sampling concept](https://opencensus.io/tracing/sampling/probabilistic/)
* Remove `enabled` option 
   - to turn off trace, user can set `samplingRate` to 0
   - With samplingRate=0, Start Trace Span operation in opencensus will not hurt performance. 

```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: myappconfig
  namespace: app_namespace
spec:
  tracing:
    samplingRate: 0.001
```

### Changed behaviors

* Track the headers that has `dapr-` prefix into span annotation instead of having `expandParams`.
   - Instead of exporting all headers in HTTP or gRPC requests, user can selectively expose the headers to trace span on their demands; if we export all headers, authentication token will be exposed to trace which will be a security violation or if the headers include users' PII, it will be GDPR violation. 
* Track response status and body in the span

### App-level configuration

App-level configuration is crucial in production environment when devops investigates the incident. We will use the current tracing configuration method as is via `dapr.io/config` annotation in application deployment object/yaml.

Currently, customer can have multiple configurations at namespace level and select configuration at app-level by using `dapr.io/config` annotation. Assume we have two trace configurations in namespace.

1. prod-tracing
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: prod-tracing
  namespace: app_namespace
spec:
  tracing:
    samplingRate: 0.001
```

2. debug-tracing
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: debug-tracing
  namespace: app_namespace
spec:
  tracing:
    samplingRate: 1.0
```

In the normal production environment, all apps would use `prod-tracing` config. When the incident occurs in production environment, user can change `dapr.io/config` to `debug-tracing` for the problematic microservice app to investigate the tracing.

## Consequences

* Simplify the tracing configuration - User can configure tracing at namespace level or app level simplify
* Prevent the potential issue of trace span export due to the span annotation limitation.
* Offer the sampling option to reduce performance impact when user turns on tracing.

**Comment by yaron2** [comment] 2020-03-25 18:05
Good proposal, a few questions:

1. Will be tracing be enabled or disabled by default? I would recommend its disabled like today
2. What is the suggested value for the default sampling rate?
3. Will disabling/enabling tracing be done in Kubernetes via an annotation? if so, what does that look like?

**Comment by youngbupark** [comment] 2020-03-25 18:46
> 1. Will be tracing be enabled or disabled by default? I would recommend its disabled like today

`--trace-sample` (sample rate) will be 0 so tracing will be disabled by default.

> 2. What is the suggested value for the default sampling rate?

It depends on the user app's traffic. Normal app will be 1 (AlwaysSample)

> 3. Will disabling/enabling tracing be done in Kubernetes via an annotation? if so, what does that look like?

Yes right. Currently we use `dapr.io/config: "tracing"` to load tracing config. I would like to introduce `dapr.io/tracing` to set the sample rate per app.

For example, if the sample rate is 1/100, 
```
dapr.io/tracing: "0.01"
```

**Comment by Haishi2016** [comment] 2020-03-25 18:48
The configuration object is used in both offline mode and k8s mode. Under k8s mode, the configuration object affects ALL Dapr instances. This means you can turn on/off distributed tracing across a multi-component application at one place. If we make this a daprd parameter, we'll have to turn the knob on each instance.

**Comment by yaron2** [comment] 2020-03-25 18:50
> > 1. Will be tracing be enabled or disabled by default? I would recommend its disabled like today
> 
> `--trace-sample` (sample rate) will be 0 so tracing will be disabled by default.
> 
> > 1. What is the suggested value for the default sampling rate?
> 
> It depends on the user app's traffic. Normal app will be 1 (AlwaysSample)
> 
> > 1. Will disabling/enabling tracing be done in Kubernetes via an annotation? if so, what does that look like?
> 
> Yes right. Currently we use `dapr.io/config: "tracing"` to load tracing config. I would like to introduce `dapr.io/trace-sampling-rate` to set the sample rate per app.
> 
> For example, if the sample rate is 1/100,
> 
> ```
> dapr.io/trace-sampling-rate: "0.01"
> ```

So we're basically using the sampling rate as a dial to decide whether its on or off.
Can you make this clear in the proposal?

> The configuration object is used in both offline mode and k8s mode. Under k8s mode, the configuration object affects ALL Dapr instances. This means you can turn on/off distributed tracing across a multi-component application at one place. If we make this a daprd parameter, we'll have to turn the knob on each instance.

That's true. with the current proposal we lose the ability to globally turn it on (although not off).

**Comment by amanbha** [comment] 2020-03-25 19:09
This looks good, I have one question: It wasnt clear to me: Could you clarify if requestBody export will not be supported at all?

**Comment by shalabhms** [comment] 2020-03-25 19:17
> > 1. Will be tracing be enabled or disabled by default? I would recommend its disabled like today
> 
> `--trace-sample` (sample rate) will be 0 so tracing will be disabled by default.
> 
> > 1. What is the suggested value for the default sampling rate?
> 
> It depends on the user app's traffic. Normal app will be 1 (AlwaysSample)
> 
> > 1. Will disabling/enabling tracing be done in Kubernetes via an annotation? if so, what does that look like?
> 
> Yes right. Currently we use `dapr.io/config: "tracing"` to load tracing config. I would like to introduce `dapr.io/trace-sampling-rate` to set the sample rate per app.
> 
> For example, if the sample rate is 1/100,
> 
> ```
> dapr.io/trace-sampling-rate: "0.01"
> ```

This usage of  "--trace-sample` (sample rate) will be 0 so tracing will be disabled by default" is not intuitive. Prefer would be to --enable-tracing and have --trace-sampling-rate differently.

**Comment by shalabhms** [comment] 2020-03-25 19:25
Why can't we can have tracing enabled by default but very low sampling rate.  And in the staging/production, user can increase the sampling rate .

**Comment by Haishi2016** [comment] 2020-03-25 19:31
I agree on separating enable tracing flag and sample rate settings.

**Comment by amanbha** [comment] 2020-03-25 19:34
+1 on a separate enable flag.

**Comment by amanbha** [comment] 2020-03-25 19:34
> Why can't we can have tracing enabled by default but very low sampling rate. And in the staging/production, user can increase the sampling rate .

Yes, if there are no drawbacks for this then it should be enabled with low sampling

**Comment by youngbupark** [comment] 2020-03-25 20:15
> Why can't we have tracing enabled by default but very low sampling rate. And in the staging/production, user can increase the sampling rate .
> Yes, if there are no drawbacks for this then it should be enabled with low sampling

@shalabhms @amanbha It is easy to change the default. For the simplicity, I would prefer turning off tracing as is. But we can decide later when we ship this change.

> This looks good, I have one question: It wasnt clear to me: Could you clarify if requestBody export will not be supported at all?

@amanbha yes. We have `includeBody` option, but it has not been implemented. request body size can be larger than 512 and non-utf8 characters. Also I think there is a chance to expose customer PII to the trace log accidentally. 

> So we're basically using the sampling rate as a dial to decide whether its on or off. Can you make this clear in the proposal?
> I agree on separating enable tracing flag and sample rate settings.

Yeah. I will add enable flag separately. @yaron2 @shalabhms @Haishi2016 @amanbha 
I will update the proposal.

**Comment by youngbupark** [comment] 2020-03-25 20:15
> The configuration object is used in both offline mode and k8s mode. Under k8s mode, the configuration object affects ALL Dapr instances. This means you can turn on/off distributed tracing across a multi-component application at one place. If we make this a daprd parameter, we'll have to turn the knob on each instance.
> That's true. with the current proposal we lose the ability to globally turn it on (although not off).

Even if user turns off the option globally, they need to restart all apps to turn it off.

Now, Dapr supports namespace level scope for CRD component configuration. Instead of having global config for trace, why not just using exporter component config to turn it on / off ?

For example, if user want to turn off the trace in namespace scope level,
1) They can delete exporter config yaml. Dapr runtime will not turn on trace even if annotation is given.
2) We can introduce new `enabled` option in exporter component config to turn on/off in the namespace scope.

@Haishi2016 @yaron2 @amanbha how do you think?

**Comment by Haishi2016** [comment] 2020-03-25 20:48
Wait, now we are talking about turning on/off at exporter level? I feel we are making this more and more complicated than necessary. As for apps picking up new configuration changes - that could be an enhancement we put in.

**Comment by youngbupark** [comment] 2020-03-25 23:29
> Wait, now we are talking about turning on/off at exporter level? I feel we are making this more and more complicated than necessary. As for apps picking up new configuration changes - that could be an enhancement we put in.

Implementation is not complicated as compared to global config. the initial proposal is to support only app level configuration and remove global tracing configuration by default like how we enable metrics. 

The proposal is basically to make tracing configuration consistent with metrics and logs.

**Comment by youngbupark** [comment] 2020-03-25 23:35
> As for apps picking up new configuration changes - that could be an enhancement we put in.

As far as I know, we will not support Dynamic config load because of jeff's suggestion. cc/ @yaron2

**Comment by Haishi2016** [comment] 2020-03-25 23:40
If we make this app-level configuration, changing tracing settings - let's say sampling frequency - will need user to update the pod spec on all participating apps (think of the distributed calculator as an example) and re-deploy the pods.  I don't see how this is simpler/better than updating one configuration and restarting the pods.

**Comment by youngbupark** [comment] 2020-03-25 23:54
> If we make this app-level configuration, changing tracing settings - let's say sampling frequency - will need user to update the pod spec on all participating apps (think of the distributed calculator as an example) and re-deploy the pods. I don't see how this is simpler/better than updating one configuration and restarting the pods.

`simpler` means to reduce one step to set up the tracing. I am not sure how frequently user will change the sampling rate.

Actually, I am fine with either ways as long as we're agree with the change of `expandparams` and `includebody` options.  :) 

If we keep using global config,
1. add sampling rate option to global config
2. remove expandParams and includeBody options

If we use app-level config,
1. Remove global config
2. add `--enable-tracing` and `--trace-sampling-rate` to daprd config

@Haishi2016 @amanbha @yaron2 @shalabhms

**Comment by yaron2** [comment] 2020-03-26 16:13
I want to the find the way that would enable:

1. Keeping a global configuration
2. Requiring changes in as little places as possible

**Comment by yaron2** [comment] 2020-03-26 16:18
So the global config options in @youngbupark message.

```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
spec:
  tracing:
    enabled: true
    samplingRate: 0.5
```

**Comment by youngbupark** [comment] 2020-03-26 16:19
> I want to the find the way that would enable:
> 
> 1. Keeping a global configuration
> 2. Requiring changes in as little places as possible

Changing code for two ways is trivial, but we need to focus on customer scenario. The reason why I came up with removing global config entirely, while working with users via issues, multiple steps introduces multiple setup combinations, which makes them confused. BTW, I am fine with either ways.

**Comment by amanbha** [comment] 2020-03-26 22:36
After reading this whole thread, I believe:
- A global configuration for cluster wide control. To set customers on correct path this is enabled by default in k8s (like mTLS) with low sampling rate.
- Then more granular controls as you are suggesting (if user wants to configure it differently for each app) but they are only appllied only when its enabled globally. If global is disabled, this is ingored.

This would mean following:
- By default, in k8sdoesnt need to do anything and its enabled with minimal sampling.
- To change global sampling rate or disable its a global config change.
- User only needs to provide on each app basis if he wants different level for each app.

Thoughts?

**Comment by lynn-orrell** [comment] 2020-03-27 06:33
Could we get rid of the required configuration but keep sane defaults? For example, by default, tracing would be enabled at a samplingRate of 0.5. If a global configuration manifest is present, it would override the baked in daprd defaults.

Then, also allow command line args (and annotations for k8s deployments) that you could set to override the defaults?

So, you'd have:
- daprd baked in defaults (tracing on / sampling 0.5)
- global configuration (if present, this would override the daprd baked in defaults)
- cmd line / annotations (if present, this would override both of the other options)

Thoughts?

@youngbupark @Haishi2016 @amanbha @yaron2 @shalabhms

**Comment by RicardoNiepel** [comment] 2020-04-01 14:35
I really love @amanbha and @lynn-orrell suggestions and would clearly vote for these.

**Comment by youngbupark** [comment] 2020-04-08 01:15
@Haishi2016 @yaron2 @amanbha  @shalabhms @RicardoNiepel @lynn-orrell 

Thanks for all your feedbacks. I've updated the proposal based on your feedbacks. When it comes to minimum sampling rate, we can adjust it later. I could not come up with good number now. 

Please review it again.

cc/ @msfussell @orizohar

**Comment by lynn-orrell** [comment] 2020-04-08 02:21
I think the revised proposal looks great, @youngbupark!

**Comment by amanbha** [comment] 2020-04-08 02:32
@youngbupark Thanks for incorporating the feedback, it looks good!

**Comment by msfussell** [comment] 2020-04-08 04:43
I have several comments on this proposal and most of them stem around configuration in general, which goes beyond just this tracing example.

1) I would prefer in the example configure file that the metadata name was not "tracing", but "myappconfig" so it makes it clear that config is more than just tracing setting, e.g. security settings
2) Are we now saying that *all* tracing setting are going to be parameters on daprd and kubernetes annotations? This seems to be a duplicate of config, so why then have a config file? And what happens when there are 100 config settings in time? Currently you apply a config file to the application, can I still do that?
3) Why are all the names of "parameters" names different? Look at the names below carefully

- dapr.io/trace-enabled
- dapr.io/trace-sample-rate

  tracing:
    enabled: true
    samplingRate: 0.5

--enable-trace: Enable tracing, default: true
--trace-sample-rate: Default trace sampling rate, default: 0.001 (1/1000) ?

4) Is the default every 1/1000th of a second or minute or hour?
5) What does this mean "user can selectively expose the headers to trace span on their demands; " please explain how a person (user) does this.

**Comment by youngbupark** [comment] 2020-04-08 16:23
> I have several comments on this proposal and most of them stem around configuration in general, which goes beyond just this tracing example.
> 
> 1. I would prefer in the example configure file that the metadata name was not "tracing", but "myappconfig" so it makes it clear that config is more than just tracing setting, e.g. security settings

You can choose any `metadata.name`s

> 2. Are we now saying that _all_ tracing setting are going to be parameters on daprd and kubernetes annotations? This seems to be a duplicate of config, so why then have a config file? And what happens when there are 100 config settings in time? Currently you apply a config file to the application, can I still do that?

Yes, `dapr.io/config` is still available. 

> 3. Why are all the names of "parameters" names different? Look at the names below carefully
> 
> * dapr.io/trace-enabled
> * dapr.io/trace-sample-rate
>   tracing:
>   enabled: true
>   samplingRate: 0.5
> 
> --enable-trace: Enable tracing, default: true
> --trace-sample-rate: Default trace sampling rate, default: 0.001 (1/1000) ?

Changed them to the consistent naming

> 1. Is the default every 1/1000th of a second or minute or hour?

No, this is not time-based sampling. please read [opencensus  probability sampler](https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/Sampling.md#what-kind-of-samplers-does-opencensus-support).  

Technically, it depends on Trace ID. Opencensus generates trace id using uniform distribution random generator. It takes upper 8 bytes(64 bits) from trace id and compare (sample rate * (1<<64)) to decide if span is emitted or not.

> 2. What does this mean "user can selectively expose the headers to trace span on their demands; " please explain how a person (user) does this.

This is the way to resolve `expandParams` option's potential security, PII leaking issues(leaking authorization token, user information, etc) because this option populates **ALL** http  or grpc headers to span annotation. Instead of having this option, user can selectively populate the header to trace span if they use `dapr-` prefix.

**Comment by youngbupark** [comment] 2020-04-08 23:26
Follow-up questions:

1. Probabilistic Sampler ? RateLimiting Sampler ?
Unfortunately, Go SDK doesn't implement RateLimiting sampler. [Only Ruby SDK](https://github.com/search?p=2&q=org%3Acensus-instrumentation+ratelimiting&type=Code) has RateLimiting sampler.

2. Can we turned off tracing by setting samplingrate to 0.0 without overhead?
Yes, here is the call flow.

Once application calls `StartSpanWithRemoteParent` to start new span, it will first call the current sampler to decide if span will be sampled or not. This if statement will be skipped if parent's sample flag is given.

https://github.com/census-instrumentation/opencensus-go/blob/46dfec7deb6e8c5d4a46f355c0da7c6d6dc59ba4/trace/trace.go#L225-L230

Then, it will check the parent's span sampling status. if it is false, then it returns immediately. So even if the app's sampling rate is 1, trace span will be discarded because parent span was not sampled.

https://github.com/census-instrumentation/opencensus-go/blob/46dfec7deb6e8c5d4a46f355c0da7c6d6dc59ba4/trace/trace.go#L233

So I do not see any performance degradation when we remove `enabled` option.

So the conclusion is :
1. Keep using probabilistic sampler but  document it correctly. 
2. Remove `enabled`. User can set samplingRate to 0 to turn off recording span without performance hurts. Also It will not break the downstream trace spans.

cc/ @yaron2 @amanbha @Haishi2016 @shalabhms @msfussell @orizohar

**Comment by youngbupark** [comment] 2020-04-09 17:00
@yaron2 @amanbha @Haishi2016 @shalabhms @msfussell @orizohar 

I revised the proposal based on the meeting feedbacks. Please review it again.

**Comment by amanbha** [comment] 2020-04-09 17:08
Thanks @youngbupark LGTM

**Closed** 2020-04-14 20:31 UTC
Labels: Epic, P1, breaking change, kind/observability
