### ISSUE TITLE
dapr uninstall --kubernetes show errors even if it is succeeded

### ISSUE THREAD

**Issue by pruthvidhodda** [dapr/dapr#1213] opened 2020-03-09 20:30 UTC
## In what area(s)?
> /area runtime

## What version of Dapr?
> 0.4.x

## Expected Behavior

dapr uninstall --kubernetes shouldn't show error when succeeded

## Actual Behavior

dapr uninstall --kubernetes shows the error even when succeeded

## Steps to Reproduce the Problem

1. dapr install --kubernetes
2. make sure dapr is installed in kubernetes
3. dapr uninstall --kuberentes

This issue is related to a [dapr/cli issue](https://github.com/dapr/cli/issues/285)

**Comment by yaron2** [comment] 2020-03-10 06:12
This issue is a dupe of the CLI issue. Should be in CLI only.

**Closed by yaron2** 2020-03-10 06:12 UTC
Labels: kind/bug
