### ISSUE TITLE
Dapr returns 200 response instead of 302 for application redirect (version 1.10.2)

### ISSUE THREAD

**Issue by caiwenhao** [dapr/dapr#6028] opened 2023-03-07 04:11 UTC
I encountered an issue while using Dapr version 1.10.2. My application returns a 302 redirect, but Dapr returns a 200 response, which prevents my application from redirecting properly. I have checked both my application and backend services, and confirmed that the issue is not with them, but with Dapr.

Here is the request log, which may help you better understand the issue:
`2023-03-07 11:29:28.011 {c4f15660af7c6013ce03ba3d52ffc98d} 302 "GET https 127.0.0.1:8080 /authorize?hmac=xxxxxx%3D%3D&shop=https%3A%2F%2Fyixixi.xxxxx.top&timestamp=1678159766 HTTP/1.1" 0.031, "https://xxxxxxx/", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"`

I would appreciate it if the Dapr project maintainers could look into this issue and fix it in the next version. Thank you for your contributions and support to the Dapr open-source project.

**Comment by Taction** [comment] 2023-03-09 12:33
Dapr uses the go http client to send the request, which follows the redirect rule and automatically sends the request to your redirected Location.

**Comment by klemmchr** [comment] 2023-03-09 19:51
@Taction this probably has nothing to do with the Go Http Client itself. This is a breaking change introduced in 1.10.0 which is not documented anywhere. Just spend three hours debugging this problem just to find out that the sidecar now magically resolves redirects.

How can I disable this to get the previous behavior?

**Comment by yaron2** [comment] 2023-03-10 07:51
@caiwenhao we're taking a look.

@klemmchr this is not documented because this behavior wasn't intended. can you confirm you don't experience this in 1.9.x?

**Comment by Taction** [comment] 2023-03-10 08:03
FYI, I switched to 1.9 and don't experience this. The core reason may be that Dapr switches HTTP client from fasthttp to go net/http. In fact, dapr does not resolve redirects, go net/http client dose. see:https://cs.opensource.google/go/go/+/master:src/net/http/client.go;l=630-689

**Comment by klemmchr** [comment] 2023-03-10 08:08
> @klemmchr this is not documented because this behavior wasn't intended. can you confirm you don't experience this in 1.9.x?

Yes, I definitely can. We are using daprd with docker compose and specified the `latest` tag. One of my colleagues had weird redirect issues I couldn't reproduce. Upon pulling the docker images the issue appeared on my machine as well. After downgrading to `1.9.6` this issue disappeared.

**Comment by Taction** [comment] 2023-03-10 08:14
@yaron2 If this behavior wasn't intended, I can work on this. Adding a `CheckRedirect` which returns the `ErrUseLastResponse` to the client may solve this.

**Comment by yaron2** [comment] 2023-03-10 08:17
@Taction thanks, it would be great if you can find first what caused the regression between 1.9 and 1.10

**Comment by berndverst** [comment] 2023-03-10 22:17
> @Taction thanks, it would be great if you can find first what caused the regression between 1.9 and 1.10

It seems the `fasthttp` to `net/http` switch did that as @Taction stated.

I wonder whether we should provide an option to follow the redirects though. We can default to the behavior not to follow them for backwards compatibility.

**Comment by yaron2** [comment] 2023-03-10 23:56
This is now fixed and will come out with 1.10.3 next week.

Thank you @Taction for helping out here!

**Comment by yaron2** [comment] 2023-03-10 23:57
Fixed via #6056

**Closed by yaron2** 2023-03-10 23:57 UTC
Labels: kind/bug, P0
