### ISSUE TITLE
Accessing Dapr secret store early on during Startup

### ISSUE THREAD

**Issue by altinoren** [dapr/dapr#2011] opened 2020-09-09 13:18 UTC
I want to use Dapr secret stores to initialize a DB connection with the connection string retrieved from a store. I want to understand the startup sequence and determine the point where secrets are available.

This is my `Main`:

``` csharp

                var host = CreateHostBuilder(args).Build(); // An OOB host builder, calling `Startup` as usual
                host.MigrateDbContext<MyDBContext>((context, services) => {
                    // DB migration code first. Host is not up ATM.
                });
                host.Run();
```

Normally, in `Startup.cs:ConfigureServices`, connection strings are supplied as follows:

``` csharp
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers().AddDapr();

            services.AddDbContext<MyDBContext>(options =>
               options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

            // ... others
        }
```

To access Dapr through DI, tried this:

``` csharp
            services.AddDbContextPool<MyDBContext>((IServiceProvider sp, DbContextOptionsBuilder options) =>
            {
                var dapr = sp.GetRequiredService<DaprClient>();
                var keys = dapr.GetSecretAsync("localsecrets", "DBConnectionString").AsTask().Result
                options.UseSqlServer(keys["DBConnectionString"]);
            });
```

In this case, Dapr is called pretty early on, before `host.Run()`. And I receive "_Error starting gRPC call: Connection refused_".  `GetSecretAsync` executes without a problem when called in a controller in my test project.

I can see that Dapr blocks while waiting to discover the application on given port and without `host.Run()`, that'll never going to happen.

Should we assume that any Dapr service is not available during Startup sequence?

**Comment by amanbha** [comment] 2020-09-09 16:23
Transferring to dapr repo and closing as duplicate of https://github.com/dapr/dapr/issues/1493

**Closed by amanbha** 2020-09-09 16:23 UTC
