### ISSUE TITLE
Incorrect error codes on access to denied resources

### ISSUE THREAD

**Issue by mchmarny** [dapr/dapr#2323] opened 2020-10-25 16:54 UTC
When trying to access resources (secrets, topic, app) to which the access has been explicitly denied, Dapr should return consistent error codes (e.g. 403). Like In Dapr v0.11.2, when trying to access secret that is not in the `allowedSecrets` on app that has `defaultAccess` set to `deny` in the configuration Dapr returns, as expected, `403 Forbidden`. 

However, when trying to publish to a topic which is not listed in the Pub/Sub component `publishingScopes` the HTTP status code returned is `500 Internal Server Error`, even though the error indicates lack of access:

```json
{
  "errorCode":"ERR_PUBSUB_PUBLISH_MESSAGE",
  "message":"topic test is not allowed for app id app2"
}
```

Similarly when trying to invoke an app from an app which is not listed in the `allow` access control policy, the HTTP status code returned is `500`, even though the error indicates lack of access:

```json
{
  "errorCode":"ERR_DIRECT_INVOKE",
  "message":"rpc error: code = PermissionDenied desc = access control policy has denied access to appid: nginx-ingress operation: counter verb: POST"
}
```

**Comment by youngbupark** [comment] 2020-10-26 15:08
Changing 500 to 403 statuscode makes sense for pubsub.  @yaron2  any thoughts ?

@vinayada1 Can you please double-check why it returns 500 instead of 403?

```
{
  "errorCode":"ERR_DIRECT_INVOKE",
  "message":"rpc error: code = PermissionDenied desc = access control policy has denied access to appid: nginx-ingress operation: counter verb: POST"
}
```

**Comment by mchmarny** [comment] 2020-10-28 00:02
#2338

**Comment by jigargandhi** [comment] 2020-10-30 14:00
I can take this up if unassigned

**Comment by artursouza** [comment] 2020-11-03 01:56
@wcs1only  Please, check if the work on this issue is included in #2338, if so, close this.

**Comment by wcs1only** [comment] 2020-11-09 19:32
Keeping this separate from #2338 (which is ready), while I figure out a good way to surface this error from the Publish callback function.

**Comment by wcs1only** [comment] 2020-12-01 00:44
Fix is out for the pubsub issue. As for direct Invoke, Mark and I were unable to reproduce, so this may have been fixed already as part of another effort.

**Closed** 2020-12-01 22:50 UTC
Labels: P1, area/runtime/invoke, area/runtime/pubsub, breaking-change, discussion, kind/bug, size/XS
