### ISSUE TITLE
[Workflows] Corrupt json input in workflow history

### ISSUE THREAD

**Issue by clintsinger** [dapr/dapr#6905] opened 2023-09-08 16:55 UTC
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.11.2

## Expected Behavior

Workflows should be able to correctly decode their history.

## Actual Behavior

When executing workflows they are failing to complete due to some corruption on data that should be JSON.  
```
{"app_id":"core-tags","instance":"garrison-core-tags-7f7fb5bc7d-g7w6t","level":"error","msg":"Error executing reminder for actor dapr.internal.garrison.core-tags.activity||ContentBuilderWorkflow_060941ac-9d22-47e7-b5b4-95d54159a32a::4::1||run-activity: unrecognized internal actor reminder payload: unexpected end of JSON input","scope":"dapr.runtime.actor","time":"2023-09-08T16:36:36.000170068Z","type":"log","ver":"1.11.2"}
```
When looking at the database (in this case postgresql) it appears that there is base64 directly in the json column.  The `isbinary` column is set to true so I suspect the data should be binary but also wrapped in json to be valid for the json parser.

![image](https://github.com/dapr/dapr/assets/1449736/c06d6216-d325-4ff0-b1d5-a3b915b00f18)

## Steps to Reproduce the Problem

1) Run any workflow

The environment is kubernetes using postgresql as the state store, though redis exhibited the same issue.

## Release Note

RELEASE NOTE:

**Comment by cgillum** [comment] 2023-09-08 19:45
The history isn't supposed to be JSON. It's supposed to be protobuf. According to this error message, the problem is not with reading the history, but with the actor reminder payload.

> unrecognized internal actor reminder payload

This sounds like a bug that was fixed here: https://github.com/dapr/dapr/pull/6795

**Comment by ItalyPaleAle** [comment] 2023-09-08 20:11
If this was fixed by #6795, can we close this?

**Comment by clintsinger** [comment] 2023-09-08 20:27
I'm currently running the edge build and I have yet to see the issue occur since updating.

**Comment by yaron2** [comment] 2023-09-08 20:27
> I'm currently running the edge build and I have yet to see the issue occur since updating.

Thanks for confirming, closing for now.

**Closed by yaron2** 2023-09-08 20:27 UTC
Labels: kind/bug
